/**
 * koko.app — Almanca Kelime Veritabanı
 *
 * Her seviye 4 kategoriye ayrılmıştır:
 *   harfler   → Alfabe harfleri
 *   rakamlar  → Sayılar
 *   kelimeler → Kelime dağarcığı
 *   cumleler  → Cümleler, kalıplar & deyimler
 *
 * Admin panelinden yapılan değişiklikler localStorage'a kaydedilir
 * ve bu varsayılan veriler yerine kullanılır.
 */

const KATEGORILER = [
  { id: 'harfler',   label: 'Harfler',   icon: '🔤' },
  { id: 'rakamlar',  label: 'Rakamlar',  icon: '🔢' },
  { id: 'kelimeler', label: 'Kelimeler', icon: '📖' },
  { id: 'cumleler',  label: 'Cümleler',  icon: '💬' }
];

const VERITABANI = {

  /* ═══ A1.1 ════════════════════════════════════════════════════════════════ */
  a11: {
    harfler: [
      { de:'a',  tr:'a (harf)',  phonetic:'[aː]',       type:'harf' },
      { de:'b',  tr:'be',       phonetic:'[beː]',       type:'harf' },
      { de:'c',  tr:'ce',       phonetic:'[tseː]',      type:'harf' },
      { de:'d',  tr:'de',       phonetic:'[deː]',       type:'harf' },
      { de:'e',  tr:'e (harf)', phonetic:'[eː]',        type:'harf' },
      { de:'f',  tr:'ef',       phonetic:'[ɛf]',        type:'harf' },
      { de:'g',  tr:'ge',       phonetic:'[ɡeː]',       type:'harf' },
      { de:'h',  tr:'ha',       phonetic:'[haː]',       type:'harf' },
      { de:'i',  tr:'i (harf)', phonetic:'[iː]',        type:'harf' },
      { de:'j',  tr:'jot',      phonetic:'[jɔt]',       type:'harf' },
      { de:'k',  tr:'ka',       phonetic:'[kaː]',       type:'harf' },
      { de:'l',  tr:'el',       phonetic:'[ɛl]',        type:'harf' },
      { de:'m',  tr:'em',       phonetic:'[ɛm]',        type:'harf' },
      { de:'n',  tr:'en',       phonetic:'[ɛn]',        type:'harf' },
      { de:'o',  tr:'o (harf)', phonetic:'[oː]',        type:'harf' },
      { de:'p',  tr:'pe',       phonetic:'[peː]',       type:'harf' },
      { de:'q',  tr:'ku',       phonetic:'[kuː]',       type:'harf' },
      { de:'r',  tr:'er',       phonetic:'[ɛʁ]',        type:'harf' },
      { de:'s',  tr:'es',       phonetic:'[ɛs]',        type:'harf' },
      { de:'t',  tr:'te',       phonetic:'[teː]',       type:'harf' },
      { de:'u',  tr:'u (harf)', phonetic:'[uː]',        type:'harf' },
      { de:'v',  tr:'fau',      phonetic:'[faʊ]',       type:'harf' },
      { de:'w',  tr:'ve',       phonetic:'[veː]',       type:'harf' },
      { de:'x',  tr:'iks',      phonetic:'[ɪks]',       type:'harf' },
      { de:'y',  tr:'üpsilon',  phonetic:'[ˈʏpsilɔn]', type:'harf' },
      { de:'z',  tr:'zet',      phonetic:'[tsɛt]',      type:'harf' },
      { de:'ä',  tr:'a umlaut', phonetic:'[ɛː]',        type:'harf' },
      { de:'ö',  tr:'o umlaut', phonetic:'[øː]',        type:'harf' },
      { de:'ü',  tr:'ü umlaut', phonetic:'[yː]',        type:'harf' },
      { de:'ß',  tr:'es-zet',   phonetic:'[ɛsˈtsɛt]',  type:'harf' }
    ],
    rakamlar: [
      { de:'null',     tr:'sıfır',   phonetic:'[nʊl]' },
      { de:'eins',     tr:'bir',     phonetic:'[aɪns]' },
      { de:'zwei',     tr:'iki',     phonetic:'[tsvaɪ]' },
      { de:'drei',     tr:'üç',      phonetic:'[dʁaɪ]' },
      { de:'vier',     tr:'dört',    phonetic:'[fiːɐ]' },
      { de:'fünf',     tr:'beş',     phonetic:'[fʏnf]' },
      { de:'sechs',    tr:'altı',    phonetic:'[zɛks]' },
      { de:'sieben',   tr:'yedi',    phonetic:'[ˈziːbən]' },
      { de:'acht',     tr:'sekiz',   phonetic:'[axt]' },
      { de:'neun',     tr:'dokuz',   phonetic:'[nɔɪn]' },
      { de:'zehn',     tr:'on',      phonetic:'[tseːn]' },
      { de:'elf',      tr:'on bir',  phonetic:'[ɛlf]' },
      { de:'zwölf',    tr:'on iki',  phonetic:'[tsvœlf]' },
      { de:'zwanzig',  tr:'yirmi',   phonetic:'[ˈtsvantsɪç]' },
      { de:'dreißig',  tr:'otuz',    phonetic:'[ˈdʁaɪsɪç]' },
      { de:'vierzig',  tr:'kırk',    phonetic:'[ˈfɪʁtsɪç]' },
      { de:'fünfzig',  tr:'elli',    phonetic:'[ˈfʏnftsɪç]' },
      { de:'sechzig',  tr:'altmış',  phonetic:'[ˈzɛçtsɪç]' },
      { de:'siebzig',  tr:'yetmiş',  phonetic:'[ˈziːptsɪç]' },
      { de:'achtzig',  tr:'seksen',  phonetic:'[ˈaxtsɪç]' },
      { de:'neunzig',  tr:'doksan',  phonetic:'[ˈnɔɪntsɪç]' },
      { de:'hundert',  tr:'yüz',     phonetic:'[ˈhʊndɐt]' },
      { de:'tausend',  tr:'bin',     phonetic:'[ˈtaʊzənt]' }
    ],
    kelimeler: [
      { de:'rot',          tr:'kırmızı',       phonetic:'[ʁoːt]' },
      { de:'blau',         tr:'mavi',          phonetic:'[blaʊ]' },
      { de:'grün',         tr:'yeşil',         phonetic:'[ɡʁyːn]' },
      { de:'gelb',         tr:'sarı',          phonetic:'[ɡɛlp]' },
      { de:'schwarz',      tr:'siyah',         phonetic:'[ʃvaʁts]' },
      { de:'weiß',         tr:'beyaz',         phonetic:'[vaɪs]' },
      { de:'grau',         tr:'gri',           phonetic:'[ɡʁaʊ]' },
      { de:'braun',        tr:'kahverengi',    phonetic:'[bʁaʊn]' },
      { de:'ja',           tr:'evet',          phonetic:'[jaː]' },
      { de:'nein',         tr:'hayır',         phonetic:'[naɪn]' },
      { de:'und',          tr:'ve',            phonetic:'[ʊnt]' },
      { de:'aber',         tr:'ama / fakat',   phonetic:'[ˈaːbɐ]' },
      { de:'nicht',        tr:'değil',         phonetic:'[nɪçt]' },
      { de:'hier',         tr:'burada',        phonetic:'[hiːɐ]' },
      { de:'dort',         tr:'orada',         phonetic:'[dɔʁt]' },
      { de:'jetzt',        tr:'şimdi',         phonetic:'[jɛtst]' },
      { de:'sehr',         tr:'çok',           phonetic:'[zeːɐ]' },
      { de:'alles',        tr:'her şey',       phonetic:'[ˈalɐs]' },
      { de:'die Mutter',   tr:'anne',          phonetic:'[ˈmʊtɐ]',      article:'die' },
      { de:'der Vater',    tr:'baba',          phonetic:'[ˈfaːtɐ]',     article:'der' },
      { de:'der Bruder',   tr:'erkek kardeş',  phonetic:'[ˈbʁuːdɐ]',    article:'der' },
      { de:'die Schwester',tr:'kız kardeş',    phonetic:'[ˈʃvɛstɐ]',    article:'die' },
      { de:'das Kind',     tr:'çocuk',         phonetic:'[kɪnt]',        article:'das' },
      { de:'der Großvater',tr:'büyükbaba',     phonetic:'[ˈɡʁoːsˌfaːtɐ]',article:'der'},
      { de:'die Großmutter',tr:'büyükanne',    phonetic:'[ˈɡʁoːsˌmʊtɐ]', article:'die'},
      { de:'der Montag',   tr:'Pazartesi',     phonetic:'[ˈmoːntaːk]',   article:'der' },
      { de:'der Dienstag', tr:'Salı',          phonetic:'[ˈdiːnstaːk]',  article:'der' },
      { de:'der Mittwoch', tr:'Çarşamba',      phonetic:'[ˈmɪtvɔx]',    article:'der' },
      { de:'der Donnerstag',tr:'Perşembe',     phonetic:'[ˈdɔnɐstaːk]', article:'der' },
      { de:'der Freitag',  tr:'Cuma',          phonetic:'[ˈfʁaɪtaːk]',  article:'der' },
      { de:'der Samstag',  tr:'Cumartesi',     phonetic:'[ˈzamstaːk]',   article:'der' },
      { de:'der Sonntag',  tr:'Pazar',         phonetic:'[ˈzɔntaːk]',   article:'der' }
    ],
    cumleler: [
      { de:'Hallo',                tr:'Merhaba',                phonetic:'[haˈloː]',               type:'cümle' },
      { de:'Guten Morgen',         tr:'Günaydın',               phonetic:'[ˈɡuːtən ˈmɔʁɡən]',      type:'cümle' },
      { de:'Guten Tag',            tr:'İyi günler',             phonetic:'[ˈɡuːtən taːk]',          type:'cümle' },
      { de:'Guten Abend',          tr:'İyi akşamlar',           phonetic:'[ˈɡuːtən ˈaːbənt]',      type:'cümle' },
      { de:'Gute Nacht',           tr:'İyi geceler',            phonetic:'[ˈɡuːtə naxt]',           type:'cümle' },
      { de:'Auf Wiedersehen',      tr:'Hoşça kal',              phonetic:'[aʊf ˈviːdɐˌzeːən]',     type:'cümle' },
      { de:'Tschüss',              tr:'Görüşürüz',              phonetic:'[tʃʏs]',                  type:'cümle' },
      { de:'Danke',                tr:'Teşekkür ederim',        phonetic:'[ˈdaŋkə]',               type:'cümle' },
      { de:'Bitte',                tr:'Rica ederim / Lütfen',   phonetic:'[ˈbɪtə]',               type:'cümle' },
      { de:'Entschuldigung',       tr:'Pardon / Özür dilerim',  phonetic:'[ɛntˈʃʊldɪɡʊŋ]',        type:'cümle' },
      { de:'Es tut mir leid',      tr:'Üzgünüm',               phonetic:'[ɛs tuːt miːɐ laɪt]',    type:'cümle' },
      { de:'Wie geht es Ihnen',    tr:'Nasılsınız (resmi)',     phonetic:'[viː ɡeːt ɛs ˈiːnən]',  type:'cümle' },
      { de:'Wie geht es dir',      tr:'Nasılsın (samimi)',      phonetic:'[viː ɡeːt ɛs diːɐ]',    type:'cümle' },
      { de:'Mir geht es gut',      tr:'İyiyim',                 phonetic:'[miːɐ ɡeːt ɛs ɡuːt]',   type:'cümle' },
      // === veritabani.json'dan eklenen A1.1 cümleleri ===
      { de:'Wo ist die Bushaltestelle?', tr:'Otobüs durağı nerede?', type:'cümle', topic:'Ulaşım', subTopic:'Otobüs durağı' },
      { de:'Wo ist der Bahnhof?', tr:'Tren istasyonu nerede?', type:'cümle', topic:'Ulaşım', subTopic:'Tren istasyonu' },
      { de:'Ich möchte ein Ticket kaufen.', tr:'Bir bilet almak istiyorum.', type:'cümle', topic:'Seyahat', subTopic:'Bilet alma' },
      { de:'Erste Klasse oder zweite Klasse?', tr:'Birinci sınıf mı, ikinci sınıf mı?', type:'cümle', topic:'Seyahat', subTopic:'Sınıf seçimi' },
      { de:'Wo ist mein Gepäck?', tr:'Bagajım nerede?', type:'cümle', topic:'Seyahat', subTopic:'Bagaj' },
      { de:'Gibt es WLAN?', tr:'Wi-Fi var mı?', type:'cümle', topic:'Konaklama', subTopic:'İnternet' },
      { de:'Wo ist der Aufzug?', tr:'Asansör nerede?', type:'cümle', topic:'Konaklama', subTopic:'Asansör' },
      { de:'Wo ist die Treppe?', tr:'Merdiven nerede?', type:'cümle', topic:'Konaklama', subTopic:'Merdiven' },
      { de:'Das Kissen ist zu hart.', tr:'Yastık çok sert.', type:'cümle', topic:'Konaklama', subTopic:'Şikayet' },
      { de:'Ich checke aus.', tr:'Otelden ayrılıyorum.', type:'cümle', topic:'Konaklama', subTopic:'Ayrılma' },
      { de:'Bar oder mit Karte?', tr:'Nakit mi, kredi kartı mı?', type:'cümle', topic:'Ödeme', subTopic:'Ödeme şekli' },
      { de:'Wo ist der Geldautomat?', tr:'ATM nerede?', type:'cümle', topic:'Para', subTopic:'ATM' },
      { de:'Meine Mutter ist Ärztin.', tr:'Annem doktor.', type:'cümle', topic:'Aile', subTopic:'Meslek' },
      { de:'Mein Vater ist Lehrer.', tr:'Babam öğretmen.', type:'cümle', topic:'Aile', subTopic:'Meslek' },
      { de:'Mein Geschwister ist fünf Jahre alt.', tr:'Kardeşim beş yaşında.', type:'cümle', topic:'Aile', subTopic:'Yaş' },
      { de:'Meine Großmutter ist alt.', tr:'Büyükannem yaşlı.', type:'cümle', topic:'Aile', subTopic:'Yaşlılık' },
      { de:'Mein Cousin ist sehr lustig.', tr:'Kuzenim çok komik.', type:'cümle', topic:'Aile', subTopic:'Karakter' },
      { de:'Mein Onkel lebt in Berlin.', tr:'Amcam Berlin\'de yaşıyor.', type:'cümle', topic:'Aile', subTopic:'Konum' },
      { de:'Meine Tante ist verheiratet.', tr:'Teyzem evli.', type:'cümle', topic:'Aile', subTopic:'Medeni hal' },
      { de:'Meine Familie ist groß.', tr:'Ailem büyük.', type:'cümle', topic:'Aile', subTopic:'Boyut' },
      { de:'Meine Eltern sind sehr gut.', tr:'Ebeveynlerim çok iyi.', type:'cümle', topic:'Aile', subTopic:'Değerlendirme' },
      { de:'Ich frühstücke.', tr:'Kahvaltı yapıyorum.', type:'cümle', topic:'Yemek', subTopic:'Kahvaltı' },
      { de:'Ich möchte Brot.', tr:'Ekmek istiyorum.', type:'cümle', topic:'Yemek', subTopic:'Ekmek' },
      { de:'Ich trinke Milch.', tr:'Süt içiyorum.', type:'cümle', topic:'Yemek', subTopic:'İçecek' },
      { de:'Ich esse einen Apfel.', tr:'Elma yiyorum.', type:'cümle', topic:'Yemek', subTopic:'Meyve' },
      { de:'Ich möchte Kaffee trinken.', tr:'Kahve içmek istiyorum.', type:'cümle', topic:'Yemek', subTopic:'Kahve' },
      { de:'Ich mag Reis.', tr:'Pilav severim.', type:'cümle', topic:'Yemek', subTopic:'Pilav' },
      { de:'Geben Sie mir bitte Salz?', tr:'Tuz verir misiniz?', type:'cümle', topic:'Yemek', subTopic:'Baharat' },
      { de:'Ich esse im Restaurant.', tr:'Restoranda yemek yiyorum.', type:'cümle', topic:'Yemek', subTopic:'Restoran' },
      { de:'Die Rechnung, bitte.', tr:'Hesap lütfen.', type:'cümle', topic:'Yemek', subTopic:'Ödeme' },
      { de:'Ich möchte Wasser.', tr:'Su istiyorum.', type:'cümle', topic:'Yemek', subTopic:'Su' },
      { de:'Ich bin Vegetarier.', tr:'Vejeteryanım.', type:'cümle', topic:'Yemek', subTopic:'Diyet' },
      { de:'Ich habe eine Allergie.', tr:'Alerjim var.', type:'cümle', topic:'Yemek', subTopic:'Alerji' },
      { de:'Wie viel kostet das?', tr:'Ne kadar?', type:'cümle', topic:'Alışveriş', subTopic:'Fiyat' },
      { de:'Das ist sehr teuer.', tr:'Çok pahalı.', type:'cümle', topic:'Alışveriş', subTopic:'Fiyat' },
      { de:'Gibt es Rabatt?', tr:'İndirim var mı?', type:'cümle', topic:'Alışveriş', subTopic:'İndirim' },
      { de:'Meine Größe ist klein.', tr:'Bedenim küçük.', type:'cümle', topic:'Alışveriş', subTopic:'Beden' },
      { de:'Haben Sie das in Blau?', tr:'Mavi rengi var mı?', type:'cümle', topic:'Alışveriş', subTopic:'Renk' },
      { de:'Ist Kreditkarte möglich?', tr:'Kredi kartı geçerli mi?', type:'cümle', topic:'Alışveriş', subTopic:'Ödeme' },
      { de:'Gibt es ein anderes Modell?', tr:'Başka model var mı?', type:'cümle', topic:'Alışveriş', subTopic:'Model' },
      { de:'Das ist zu groß.', tr:'Bu çok büyük.', type:'cümle', topic:'Alışveriş', subTopic:'Boyut' },
      { de:'Das ist zu eng.', tr:'Bu çok dar.', type:'cümle', topic:'Alışveriş', subTopic:'Boyut' },
      { de:'Ich zahle mit Karte.', tr:'Kartla ödüyorum.', type:'cümle', topic:'Alışveriş', subTopic:'Ödeme' },
      { de:'Ich zahle bar.', tr:'Nakit ödüyorum.', type:'cümle', topic:'Alışveriş', subTopic:'Ödeme' },
      { de:'Ich fühle mich nicht gut.', tr:'Kendimi iyi hissetmiyorum.', type:'cümle', topic:'Sağlık', subTopic:'Hasta' },
      { de:'Ich habe Kopfschmerzen.', tr:'Başım ağrıyor.', type:'cümle', topic:'Sağlık', subTopic:'Ağrı' },
      { de:'Ich habe Fieber.', tr:'Ateşim var.', type:'cümle', topic:'Sağlık', subTopic:'Ateş' },
      { de:'Ich huste.', tr:'Öksürüyorum.', type:'cümle', topic:'Sağlık', subTopic:'Öksürük' },
      { de:'Rufen Sie einen Arzt.', tr:'Doktor çağırın.', type:'cümle', topic:'Sağlık', subTopic:'Doktor' },
      { de:'Wo ist die Apotheke?', tr:'Eczane nerede?', type:'cümle', topic:'Sağlık', subTopic:'Eczane' },
      { de:'Meine Nase blutet.', tr:'Burnum kanıyor.', type:'cümle', topic:'Sağlık', subTopic:'Burun kanaması' },
      { de:'Mir ist übel.', tr:'Midim bulandı.', type:'cümle', topic:'Sağlık', subTopic:'Mide bulantısı' },
    ]
  },

  /* ═══ A1.2 ════════════════════════════════════════════════════════════════ */
  a12: {
    harfler: [],
    rakamlar: [
      { de:'dreizehn',   tr:'on üç',    phonetic:'[ˈdʁaɪtseːn]' },
      { de:'vierzehn',   tr:'on dört',  phonetic:'[ˈfɪʁtseːn]' },
      { de:'fünfzehn',   tr:'on beş',   phonetic:'[ˈfʏnftseːn]' },
      { de:'sechzehn',   tr:'on altı',  phonetic:'[ˈzɛçtseːn]' },
      { de:'siebzehn',   tr:'on yedi',  phonetic:'[ˈziːptseːn]' },
      { de:'achtzehn',   tr:'on sekiz', phonetic:'[ˈaxtseːn]' },
      { de:'neunzehn',   tr:'on dokuz', phonetic:'[ˈnɔɪntseːn]' },
      { de:'eine Million',tr:'bir milyon',phonetic:'[ˈaɪnə mɪˈli̯oːn]' }
    ],
    kelimeler: [
      { de:'das Brot',    tr:'ekmek',     phonetic:'[bʁoːt]',     article:'das' },
      { de:'die Butter',  tr:'tereyağı',  phonetic:'[ˈbʊtɐ]',     article:'die' },
      { de:'der Käse',    tr:'peynir',    phonetic:'[ˈkɛːzə]',    article:'der' },
      { de:'das Ei',      tr:'yumurta',   phonetic:'[aɪ]',         article:'das' },
      { de:'die Milch',   tr:'süt',       phonetic:'[mɪlç]',      article:'die' },
      { de:'der Apfel',   tr:'elma',      phonetic:'[ˈapfəl]',    article:'der' },
      { de:'die Banane',  tr:'muz',       phonetic:'[baˈnaːnə]',  article:'die' },
      { de:'das Fleisch', tr:'et',        phonetic:'[flaɪʃ]',     article:'das' },
      { de:'der Fisch',   tr:'balık',     phonetic:'[fɪʃ]',       article:'der' },
      { de:'das Wasser',  tr:'su',        phonetic:'[ˈvasɐ]',     article:'das' },
      { de:'der Kaffee',  tr:'kahve',     phonetic:'[kaˈfeː]',    article:'der' },
      { de:'der Tee',     tr:'çay',       phonetic:'[teː]',       article:'der' },
      { de:'das Haus',    tr:'ev',        phonetic:'[haʊs]',      article:'das' },
      { de:'die Wohnung', tr:'daire',     phonetic:'[ˈvoːnʊŋ]',  article:'die' },
      { de:'das Zimmer',  tr:'oda',       phonetic:'[ˈtsɪmɐ]',   article:'das' },
      { de:'die Küche',   tr:'mutfak',    phonetic:'[ˈkʏçə]',    article:'die' },
      { de:'der Tisch',   tr:'masa',      phonetic:'[tɪʃ]',       article:'der' },
      { de:'der Stuhl',   tr:'sandalye',  phonetic:'[ʃtuːl]',     article:'der' },
      { de:'das Bett',    tr:'yatak',     phonetic:'[bɛt]',       article:'das' },
      { de:'das Fenster', tr:'pencere',   phonetic:'[ˈfɛnstɐ]',  article:'das' },
      { de:'die Tür',     tr:'kapı',      phonetic:'[tyːɐ]',      article:'die' },
      { de:'das Buch',    tr:'kitap',     phonetic:'[buːx]',      article:'das' },
      { de:'der Kopf',    tr:'baş',       phonetic:'[kɔpf]',      article:'der' },
      { de:'das Auge',    tr:'göz',       phonetic:'[ˈaʊɡə]',    article:'das' },
      { de:'die Nase',    tr:'burun',     phonetic:'[ˈnaːzə]',   article:'die' },
      { de:'der Mund',    tr:'ağız',      phonetic:'[mʊnt]',      article:'der' },
      { de:'die Hand',    tr:'el',        phonetic:'[hant]',       article:'die' },
      { de:'der Fuß',     tr:'ayak',      phonetic:'[fuːs]',      article:'der' },
      { de:'das Herz',    tr:'kalp',      phonetic:'[hɛʁts]',    article:'das' },
      { de:'das Haar',    tr:'saç',       phonetic:'[haːɐ]',      article:'das' }
    ],
    cumleler: [
      { de:'Ich heiße …',                     tr:'Benim adım …',               phonetic:'[ɪç ˈhaɪsə]',               type:'cümle' },
      { de:'Ich komme aus der Türkei',         tr:'Türkiye\'den geliyorum',      phonetic:'[ɪç ˈkɔmə aʊs]',           type:'cümle' },
      { de:'Wie alt bist du',                  tr:'Kaç yaşındasın',             phonetic:'[viː alt bɪst duː]',        type:'cümle' },
      { de:'Ich bin zwanzig Jahre alt',        tr:'Ben yirmi yaşındayım',       phonetic:'[ɪç bɪn ˈtsvantsɪç]',      type:'cümle' },
      { de:'Ich spreche ein bisschen Deutsch', tr:'Biraz Almanca konuşuyorum',  phonetic:'[ɪç ˈʃpʁɛçə aɪn ˈbɪsçən]', type:'cümle' },
      { de:'Wo wohnst du',                     tr:'Nerede oturuyorsun',         phonetic:'[voː voːnst duː]',           type:'cümle' },
      { de:'Ich bin Student',                  tr:'Ben öğrenciyim',             phonetic:'[ɪç bɪn ʃtuˈdɛnt]',         type:'cümle' },
      // === veritabani.json'dan eklenen A1.2 cümleleri ===
      { de:'Ich möchte zum Flughafen fahren.', tr:'Havaalanına gitmek istiyorum.', type:'cümle', topic:'Seyahat', subTopic:'Havaalanı' },
      { de:'Ich möchte eine einfache Fahrkarte.', tr:'Tek yön bilet istiyorum.', type:'cümle', topic:'Seyahat', subTopic:'Tek yön' },
      { de:'Ich möchte eine Rückfahrkarte.', tr:'Gidiş-dönüş bilet istiyorum.', type:'cümle', topic:'Seyahat', subTopic:'Gidiş-dönüş' },
      { de:'Ich möchte einen Fensterplatz.', tr:'Pencere kenarı istiyorum.', type:'cümle', topic:'Seyahat', subTopic:'Koltuk' },
      { de:'Ich möchte einen Gangplatz.', tr:'Koridor kenarı istiyorum.', type:'cümle', topic:'Seyahat', subTopic:'Koltuk' },
      { de:'Mein Gepäck ist verloren gegangen.', tr:'Bagajım kayboldu.', type:'cümle', topic:'Seyahat', subTopic:'Kayıp bagaj' },
      { de:'Wo ist die Passkontrolle?', tr:'Pasaport kontrolü nerede?', type:'cümle', topic:'Seyahat', subTopic:'Pasaport kontrolü' },
      { de:'Wo ist die Zollkontrolle?', tr:'Gümrük kontrolü nerede?', type:'cümle', topic:'Seyahat', subTopic:'Gümrük' },
      { de:'Wo ist der Wartesaal?', tr:'Bekleme salonu nerede?', type:'cümle', topic:'Seyahat', subTopic:'Bekleme salonu' },
      { de:'Mein Flug hat Verspätung.', tr:'Uçuşum rötar yaptı.', type:'cümle', topic:'Seyahat', subTopic:'Rötar' },
      { de:'Mein Flug ist gestrichen worden.', tr:'Uçuşum iptal edildi.', type:'cümle', topic:'Seyahat', subTopic:'İptal' },
      { de:'Gibt es einen anderen Flug?', tr:'Başka uçuş var mı?', type:'cümle', topic:'Seyahat', subTopic:'Alternatif uçuş' },
      { de:'Ich habe eine Hotelreservierung.', tr:'Otel rezervasyonum var.', type:'cümle', topic:'Konaklama', subTopic:'Rezervasyon' },
      { de:'Ich möchte ein Einzelzimmer.', tr:'Tek kişilik oda istiyorum.', type:'cümle', topic:'Konaklama', subTopic:'Tek kişilik oda' },
      { de:'Ich möchte ein Doppelzimmer.', tr:'Çift kişilik oda istiyorum.', type:'cümle', topic:'Konaklama', subTopic:'Çift kişilik oda' },
      { de:'Ist das Frühstück inklusive?', tr:'Kahvaltı dahil mi?', type:'cümle', topic:'Konaklama', subTopic:'Kahvaltı' },
      { de:'Wie lautet das Passwort?', tr:'Şifre nedir?', type:'cümle', topic:'Konaklama', subTopic:'Wi-Fi şifresi' },
      { de:'Gibt es eine Waschküche?', tr:'Çamaşırhane var mı?', type:'cümle', topic:'Konaklama', subTopic:'Çamaşırhane' },
      { de:'Könnten Sie mein Zimmer reinigen?', tr:'Odamı temizleyebilir misiniz?', type:'cümle', topic:'Konaklama', subTopic:'Temizlik' },
      { de:'Bitte wechseln Sie die Handtücher.', tr:'Havlu değiştirin lütfen.', type:'cümle', topic:'Konaklama', subTopic:'Havlu' },
      { de:'Es fehlt eine Decke.', tr:'Battaniye eksik.', type:'cümle', topic:'Konaklama', subTopic:'Eksik' },
      { de:'Können Sie die Klimaanlage einschalten?', tr:'Klimayı açabilir misiniz?', type:'cümle', topic:'Konaklama', subTopic:'Klima' },
      { de:'Die Heizung funktioniert nicht.', tr:'Isıtıcı çalışmıyor.', type:'cümle', topic:'Konaklama', subTopic:'Isıtma' },
      { de:'Ich möchte das Zimmer wechseln.', tr:'Odayı değiştirmek istiyorum.', type:'cümle', topic:'Konaklama', subTopic:'Oda değişimi' },
      { de:'Wann ist die Check-out-Zeit?', tr:'Çıkış saat kaç?', type:'cümle', topic:'Konaklama', subTopic:'Çıkış' },
      { de:'Kann ich spät auschecken?', tr:'Geç çıkış yapabilir miyim?', type:'cümle', topic:'Konaklama', subTopic:'Geç çıkış' },
      { de:'Können Sie meinen Koffer aufbewahren?', tr:'Valizimi saklayabilir misiniz?', type:'cümle', topic:'Konaklama', subTopic:'Eşya saklama' },
      { de:'Ich möchte die Rechnung bezahlen.', tr:'Hesabı ödemek istiyorum.', type:'cümle', topic:'Konaklama', subTopic:'Ödeme' },
      { de:'Akzeptieren Sie Kreditkarten?', tr:'Kredi kartı kabul ediyor musunuz?', type:'cümle', topic:'Ödeme', subTopic:'Kredi kartı' },
      { de:'Schicken Sie mir die Rechnung.', tr:'Faturayı bana gönderin.', type:'cümle', topic:'Ödeme', subTopic:'Fatura gönderme' },
      { de:'Kann ich eine Quittung bekommen?', tr:'Makbuz alabilir miyim?', type:'cümle', topic:'Ödeme', subTopic:'Makbuz' },
      { de:'Wofür ist diese Gebühr?', tr:'Bu ücret ne için?', type:'cümle', topic:'Ödeme', subTopic:'Ücret sorgulama' },
      { de:'Das ist eine falsche Berechnung.', tr:'Bu yanlış bir ücretlendirme.', type:'cümle', topic:'Ödeme', subTopic:'Hata' },
      { de:'Bitte korrigieren Sie die Gebühr.', tr:'Ücreti düzeltin lütfen.', type:'cümle', topic:'Ödeme', subTopic:'Düzeltme' },
      { de:'Das Wechselgeld stimmt nicht.', tr:'Para üstü eksik.', type:'cümle', topic:'Ödeme', subTopic:'Para üstü' },
      { de:'Ich möchte Geld wechseln.', tr:'Döviz bozdurmak istiyorum.', type:'cümle', topic:'Para', subTopic:'Döviz' },
      { de:'Wie ist der Wechselkurs?', tr:'Döviz kuru nedir?', type:'cümle', topic:'Para', subTopic:'Kur' },
      { de:'Wie hoch ist die Provision?', tr:'Komisyon ne kadar?', type:'cümle', topic:'Para', subTopic:'Komisyon' },
      { de:'Mein Neffe hat die Schule angefangen.', tr:'Yeğenim okula başladı.', type:'cümle', topic:'Aile', subTopic:'Eğitim' },
      { de:'Der Tee soll süß sein.', tr:'Çay şekerli olsun.', type:'cümle', topic:'Yemek', subTopic:'Çay' },
      { de:'Kann ich die Speisekarte sehen?', tr:'Menüyü görebilir miyim?', type:'cümle', topic:'Yemek', subTopic:'Menü' },
      { de:'Ich bin allergisch gegen Nüsse.', tr:'Fındık alerjim var.', type:'cümle', topic:'Yemek', subTopic:'Alerji' },
      { de:'Kann ich umtauschen?', tr:'Değişim yapabilir miyim?', type:'cümle', topic:'Alışveriş', subTopic:'İade' },
      { de:'Kann ich einen Beleg bekommen?', tr:'Fiş alabilir miyim?', type:'cümle', topic:'Alışveriş', subTopic:'Fiş' },
      { de:'Ich schaue mich nur um.', tr:'Sadece bakıyorum.', type:'cümle', topic:'Alışveriş', subTopic:'Bakma' },
      { de:'Das Paket ist als Geschenk.', tr:'Paket hediye olacak.', type:'cümle', topic:'Alışveriş', subTopic:'Hediye' },
      { de:'Ich muss Medikamente nehmen.', tr:'İlaç almam lazım.', type:'cümle', topic:'Sağlık', subTopic:'İlaç' },
      { de:'Ich muss mich ausruhen.', tr:'Dinlenmem gerekiyor.', type:'cümle', topic:'Sağlık', subTopic:'Dinlenme' },
    ]
  },

  /* ═══ B1.1 ════════════════════════════════════════════════════════════════ */
  b11: {
    harfler: [],
    rakamlar: [],
    kelimeler: [
      { de:'die Meinung',       tr:'görüş / fikir',      phonetic:'[ˈmaɪnʊŋ]',       article:'die' },
      { de:'der Grund',         tr:'neden / sebep',       phonetic:'[ɡʁʊnt]',          article:'der' },
      { de:'die Lösung',        tr:'çözüm',              phonetic:'[ˈløːzʊŋ]',        article:'die' },
      { de:'das Problem',       tr:'sorun',              phonetic:'[pʁoˈbleːm]',      article:'das' },
      { de:'die Erfahrung',     tr:'deneyim',            phonetic:'[ɛɐˈfaːʁʊŋ]',     article:'die' },
      { de:'die Möglichkeit',   tr:'olasılık / imkân',   phonetic:'[ˈmøːklɪçkaɪt]',  article:'die' },
      { de:'der Unterschied',   tr:'fark',               phonetic:'[ˈʊntɐˌʃiːt]',    article:'der' },
      { de:'die Entwicklung',   tr:'gelişme',            phonetic:'[ɛntˈvɪklʊŋ]',    article:'die' },
      { de:'neben',             tr:'yanında',            phonetic:'[ˈneːbən]' },
      { de:'zwischen',          tr:'arasında',           phonetic:'[ˈtsvɪʃən]' },
      { de:'hinter',            tr:'arkasında',          phonetic:'[ˈhɪntɐ]' },
      { de:'über',              tr:'üzerinde',           phonetic:'[ˈyːbɐ]' },
      { de:'unter',             tr:'altında',            phonetic:'[ˈʊntɐ]' },
      { de:'links',             tr:'solda',              phonetic:'[lɪŋks]' },
      { de:'rechts',            tr:'sağda',              phonetic:'[ʁɛçts]' },
      { de:'erklären',          tr:'açıklamak',          phonetic:'[ɛɐˈklɛːʁən]' },
      { de:'verstehen',         tr:'anlamak',            phonetic:'[fɛɐˈʃteːən]' },
      { de:'beschreiben',       tr:'tanımlamak',         phonetic:'[bəˈʃʁaɪbən]' },
      { de:'vergleichen',       tr:'karşılaştırmak',     phonetic:'[fɛɐˈɡlaɪçən]' }
    ],
    cumleler: [
      { de:'Meiner Meinung nach ist das richtig',   tr:'Benim görüşüme göre bu doğru',        phonetic:'[ˈmaɪnɐ ˈmaɪnʊŋ naːx]',   type:'cümle' },
      { de:'Ich stimme dir zu',                     tr:'Sana katılıyorum',                    phonetic:'[ɪç ˈʃtɪmə diːɐ tsuː]',   type:'cümle' },
      { de:'Ich habe das nicht verstanden',         tr:'Bunu anlayamadım',                    phonetic:'[ɪç ˈhaːbə das nɪçt]',     type:'cümle' },
      { de:'Ich lerne Deutsch seit einem Jahr',     tr:'Bir yıldır Almanca öğreniyorum',      phonetic:'[ɪç ˈlɛʁnə ˈdɔɪtʃ zaɪt]', type:'cümle' },
      { de:'Könnten Sie das bitte wiederholen',     tr:'Bunu tekrar edebilir misiniz lütfen', phonetic:'[ˈkœntən ziː das ˈbɪtə]',  type:'cümle' }
    ]
  },

  /* ═══ B1.2 ════════════════════════════════════════════════════════════════ */
  b12: {
    harfler:  [],
    rakamlar: [],
    kelimeler: [
      { de:'die Freude',       tr:'sevinç',   phonetic:'[ˈfʁɔɪdə]',       article:'die' },
      { de:'die Trauer',       tr:'üzüntü',   phonetic:'[ˈtʁaʊɐ]',        article:'die' },
      { de:'die Angst',        tr:'korku',    phonetic:'[aŋst]',           article:'die' },
      { de:'die Wut',          tr:'öfke',     phonetic:'[vuːt]',           article:'die' },
      { de:'die Hoffnung',     tr:'umut',     phonetic:'[ˈhɔfnʊŋ]',       article:'die' },
      { de:'die Überraschung', tr:'sürpriz',  phonetic:'[ˈyːbɐˌʁaʃʊŋ]',  article:'die' },
      { de:'das Vertrauen',    tr:'güven',    phonetic:'[fɛɐˈtʁaʊən]',    article:'das' },
      { de:'die Sehnsucht',    tr:'özlem',    phonetic:'[ˈzeːnzʊxt]',     article:'die' },
      { de:'sich freuen',      tr:'sevinmek', phonetic:'[zɪç ˈfʁɔɪən]' },
      { de:'zweifeln',         tr:'şüphelenmek', phonetic:'[ˈtsvaɪfəln]' }
    ],
    cumleler: [
      { de:'Obwohl es schwer ist, gebe ich nicht auf', tr:'Zor olsa da pes etmiyorum',                  phonetic:'[ɔpˈvoːl ɛs ʃveːɐ ɪst]', type:'cümle' },
      { de:'Je mehr ich übe, desto besser werde ich', tr:'Ne kadar çok çalışırsam o kadar iyi olurum', phonetic:'[jeː meːɐ ɪç ˈyːbə]',      type:'cümle' },
      { de:'Ich hätte gern einen Kaffee',              tr:'Bir kahve isterdim',                         phonetic:'[ɪç ˈhɛtə ɡɛʁn ˈaɪnən]',   type:'cümle' }
    ]
  },

  /* ═══ B2.1 ════════════════════════════════════════════════════════════════ */
  b21: {
    harfler: [],
    rakamlar: [],
    kelimeler: [
      { de:'die Analyse', tr:'analiz', phonetic:'[aˈnalyːzə]', article:'die' },
      { de:'der Bericht', tr:'rapor', phonetic:'[bəˈʁɪçt]', article:'der' },
      { de:'die Strategie', tr:'strateji', phonetic:'[ʃtʁateˈɡiː]', article:'die' },
      { de:'das Ergebnis', tr:'sonuç', phonetic:'[ɛɐˈɡeːpnɪs]', article:'das' },
      { de:'die Herausforderung', tr:'meydan okuma / zorluk', phonetic:'[hɛˈʁaʊsfɔʁdəʁʊŋ]', article:'die' },
      { de:'der Fortschritt', tr:'ilerleme', phonetic:'[ˈfɔʁtʃʁɪt]', article:'der' },
      { de:'die Auswirkung', tr:'etki / sonuç', phonetic:'[ˈaʊsvɪʁkʊŋ]', article:'die' },
      { de:'der Zusammenhang', tr:'bağlantı / ilişki', phonetic:'[tsuˈzamənhaŋ]', article:'der' },
      { de:'die Voraussetzung', tr:'ön koşul', phonetic:'[foˈʁaʊszɛtsʊŋ]', article:'die' },
      { de:'das Risiko', tr:'risk', phonetic:'[ˈʁiːziko]', article:'das' },
      { de:'der Einfluss', tr:'etki / nüfuz', phonetic:'[ˈaɪnflʊs]', article:'der' },
      { de:'die Umsetzung', tr:'uygulama / hayata geçirme', phonetic:'[ˈʊmzɛtsʊŋ]', article:'die' },
      { de:'das Ziel', tr:'hedef / amaç', phonetic:'[tsiːl]', article:'das' },
      { de:'die Maßnahme', tr:'tedbir / önlem', phonetic:'[ˈmaːsnaːmə]', article:'die' },
      { de:'der Zeitraum', tr:'zaman dilimi', phonetic:'[ˈtsaɪtʁaʊm]', article:'der' },
      { de:'die Tendenz', tr:'eğilim', phonetic:'[tɛnˈdɛnts]', article:'die' },
      { de:'sich beziehen auf', tr:'... ile ilgili olmak', phonetic:'[zɪç bəˈtsiːən aʊf]' },
      { de:'nachweisen', tr:'kanıtlamak', phonetic:'[ˈnaːxvaɪzən]' },
      { de:'bewirken', tr:'neden olmak / sağlamak', phonetic:'[bəˈvɪʁkən]' },
      { de:'voraussetzen', tr:'öngermek / gerektirmek', phonetic:'[foˈʁaʊszɛtsən]' },
      { de:'berücksichtigen', tr:'göz önünde bulundurmak', phonetic:'[bəˈʁʏkzɪçtɪɡən]' },
      { de:'abwägen', tr:'tartmak / değerlendirmek', phonetic:'[ˈapvɛːɡən]' },
      { de:'aufweisen', tr:'göstermek / sahip olmak', phonetic:'[ˈaʊfvaɪzən]' },
      { de:'umfassen', tr:'kapsamak', phonetic:'[ʊmˈfasən]' },
      { de:'darstellen', tr:'temsil etmek / göstermek', phonetic:'[ˈdaːʁʃtɛlən]' }
    ],
    cumleler: [
      { de:'Die finanziellen Ressourcen sind unzureichend.', tr:'Mali kaynaklar yetersiz.', type:'cümle', topic:'İş', subTopic:'Kaynak', cefr:'B2.1' },
      { de:'Der Zeitplan ist nicht realistisch.', tr:'Zaman çizelgesi gerçekçi değil.', type:'cümle', topic:'İş', subTopic:'Zamanlama', cefr:'B2.1' },
      { de:'Die Marktanalyse ist lückenhaft.', tr:'Pazar araştırması eksik.', type:'cümle', topic:'İş', subTopic:'Pazar', cefr:'B2.1' },
      { de:'Die Kundenzufriedenheit nimmt ab.', tr:'Müşteri memnuniyeti düşüyor.', type:'cümle', topic:'İş', subTopic:'Müşteri', cefr:'B2.1' },
      { de:'Die Verkaufszahlen liegen unter den Erwartungen.', tr:'Satış rakamları beklentilerin altında.', type:'cümle', topic:'İş', subTopic:'Satış', cefr:'B2.1' },
      { de:'Wir müssen die Kosten senken.', tr:'Maliyetleri düşürmemiz gerekiyor.', type:'cümle', topic:'İş', subTopic:'Maliyet', cefr:'B2.1' },
      { de:'Wir sollten die Effizienz steigern.', tr:'Verimliliği artırmalıyız.', type:'cümle', topic:'İş', subTopic:'Verimlilik', cefr:'B2.1' },
      { de:'Wir sollten in Innovationen investieren.', tr:'İnovasyona yatırım yapmalıyız.', type:'cümle', topic:'İş', subTopic:'İnovasyon', cefr:'B2.1' },
      { de:'Wir sollten die Mitarbeiter schulen.', tr:'Çalışanları eğitmeliyiz.', type:'cümle', topic:'İş', subTopic:'Eğitim', cefr:'B2.1' },
      { de:'Wir sollten den Workflow optimieren.', tr:'İş akışını optimize etmeliyiz.', type:'cümle', topic:'İş', subTopic:'Optimizasyon', cefr:'B2.1' },
      { de:'Wir sollten die Strategie überdenken.', tr:'Stratejiyi gözden geçirmeliyiz.', type:'cümle', topic:'İş', subTopic:'Strateji', cefr:'B2.1' },
      { de:'Die Besprechung sollte verschoben werden.', tr:'Toplantı ertelenmeli.', type:'cümle', topic:'İş', subTopic:'Toplantı', cefr:'B2.1' },
      { de:'Die Entscheidung wurde vertagt.', tr:'Karar askıya alındı.', type:'cümle', topic:'İş', subTopic:'Karar', cefr:'B2.1' },
      { de:'Das Thema wurde aufgegriffen.', tr:'Konu gündeme getirildi.', type:'cümle', topic:'İş', subTopic:'Gündem', cefr:'B2.1' },
      { de:'Der Vorschlag wurde abgelehnt.', tr:'Öneri reddedildi.', type:'cümle', topic:'İş', subTopic:'Ret', cefr:'B2.1' },
      { de:'Die Forderung wurde akzeptiert.', tr:'Talep kabul edildi.', type:'cümle', topic:'İş', subTopic:'Kabul', cefr:'B2.1' },
      { de:'Es wurde eine Einigung erzielt.', tr:'Anlaşmaya varıldı.', type:'cümle', topic:'İş', subTopic:'Anlaşma', cefr:'B2.1' },
      { de:'Der Vertrag wurde unterschrieben.', tr:'Sözleşme imzalandı.', type:'cümle', topic:'İş', subTopic:'Sözleşme', cefr:'B2.1' },
      { de:'Das Projekt wurde genehmigt.', tr:'Proje onaylandı.', type:'cümle', topic:'İş', subTopic:'Onay', cefr:'B2.1' },
      { de:'Das Budget wurde gekürzt.', tr:'Bütçe kesildi.', type:'cümle', topic:'İş', subTopic:'Bütçe', cefr:'B2.1' },
      { de:'Das Personal wurde reduziert.', tr:'Personel azaltıldı.', type:'cümle', topic:'İş', subTopic:'İstihdam', cefr:'B2.1' },
      { de:'Die Produktion wurde eingestellt.', tr:'Üretim durduruldu.', type:'cümle', topic:'İş', subTopic:'Üretim', cefr:'B2.1' },
      { de:'Die Filiale wurde geschlossen.', tr:'Şube kapatıldı.', type:'cümle', topic:'İş', subTopic:'Kapanış', cefr:'B2.1' },
      { de:'Ich bereite mich auf das Vorstellungsgespräch vor.', tr:'Mülakata hazırlanıyorum.', type:'cümle', topic:'İş', subTopic:'Mülakat', cefr:'B2.1' },
      { de:'Ich habe mich um die Stelle beworben.', tr:'İş başvurusu yaptım.', type:'cümle', topic:'İş', subTopic:'Başvuru', cefr:'B2.1' },
      { de:'Ich habe meine Gehaltsvorstellung genannt.', tr:'Maaş beklentimi söyledim.', type:'cümle', topic:'İş', subTopic:'Maaş', cefr:'B2.1' },
      { de:'Die Probezeit beträgt sechs Monate.', tr:'Deneme süresi altı ay.', type:'cümle', topic:'İş', subTopic:'Deneme süresi', cefr:'B2.1' },
      { de:'Ich habe Anspruch auf Abfindung.', tr:'Kıdem tazminatı hakkım var.', type:'cümle', topic:'İş', subTopic:'Tazminat', cefr:'B2.1' },
      { de:'Die Kündigungsfrist ist abgelaufen.', tr:'İhbar süresi doldu.', type:'cümle', topic:'İş', subTopic:'İhbar', cefr:'B2.1' },
      { de:'Ich habe einen Nebenjob.', tr:'Ek iş yapıyorum.', type:'cümle', topic:'İş', subTopic:'Ek iş', cefr:'B2.1' },
      { de:'Es gibt die Möglichkeit zur Remote-Arbeit.', tr:'Uzaktan çalışma imkanı var.', type:'cümle', topic:'İş', subTopic:'Uzaktan çalışma', cefr:'B2.1' },
      { de:'Ich möchte flexible Arbeitszeiten.', tr:'Esnek çalışma saatleri istiyorum.', type:'cümle', topic:'İş', subTopic:'Esnek saatler', cefr:'B2.1' },
      { de:'Ich muss Überstunden machen.', tr:'Mesai yapmak zorundayım.', type:'cümle', topic:'İş', subTopic:'Mesai', cefr:'B2.1' },
      { de:'Die Arbeitsbelastung ist sehr hoch.', tr:'İş yükü çok ağır.', type:'cümle', topic:'İş', subTopic:'İş yükü', cefr:'B2.1' },
      { de:'Die Arbeitszufriedenheit ist gering.', tr:'İş tatmini düşük.', type:'cümle', topic:'İş', subTopic:'Tatmin', cefr:'B2.1' },
      { de:'Ich möchte den Beruf wechseln.', tr:'Kariyer değişikliği yapmak istiyorum.', type:'cümle', topic:'İş', subTopic:'Kariyer değişimi', cefr:'B2.1' },
      { de:'Ich lege Wert auf Teamarbeit.', tr:'Ekip çalışmasına önem veriyorum.', type:'cümle', topic:'İş', subTopic:'Takım çalışması', cefr:'B2.1' },
      { de:'Ich habe Führungsqualitäten.', tr:'Liderlik becerilerim var.', type:'cümle', topic:'İş', subTopic:'Liderlik', cefr:'B2.1' },
      { de:'Ich habe kritisches Feedback erhalten.', tr:'Kritik geri bildirim aldım.', type:'cümle', topic:'İş', subTopic:'Geri bildirim', cefr:'B2.1' },
      { de:'Meine Leistungsbeurteilung ist positiv.', tr:'Performans değerlendirmem olumlu.', type:'cümle', topic:'İş', subTopic:'Performans', cefr:'B2.1' },
      { de:'Ich wurde befördert.', tr:'Terfi ettim.', type:'cümle', topic:'İş', subTopic:'Terfi', cefr:'B2.1' },
      { de:'Die soziale Ungleichheit nimmt zu.', tr:'Toplumsal eşitsizlik artıyor.', type:'cümle', topic:'Toplum', subTopic:'Eşitsizlik', cefr:'B2.1' },
      { de:'Er lebt unter der Armutsgrenze.', tr:'Yoksulluk sınırı altında yaşıyor.', type:'cümle', topic:'Toplum', subTopic:'Yoksulluk', cefr:'B2.1' },
      { de:'Die Bevölkerung altert.', tr:'Nüfus yaşlanıyor.', type:'cümle', topic:'Toplum', subTopic:'Yaşlanma', cefr:'B2.1' },
      { de:'Die Geburtenrate sinkt.', tr:'Doğum oranı düşüyor.', type:'cümle', topic:'Toplum', subTopic:'Doğum oranı', cefr:'B2.1' },
      { de:'Die Infrastruktur ist unzureichend.', tr:'Altyapı yetersiz.', type:'cümle', topic:'Toplum', subTopic:'Altyapı', cefr:'B2.1' },
      { de:'Der öffentliche Raum nimmt ab.', tr:'Kamusal alan azalıyor.', type:'cümle', topic:'Toplum', subTopic:'Kamusal alan', cefr:'B2.1' },
      { de:'Die soziale Mobilität ist begrenzt.', tr:'Sosyal hareketlilik sınırlı.', type:'cümle', topic:'Toplum', subTopic:'Hareketlilik', cefr:'B2.1' },
      { de:'Diskriminierung ist verboten.', tr:'Ayrımcılık yasak.', type:'cümle', topic:'Toplum', subTopic:'Ayrımcılık', cefr:'B2.1' },
      { de:'Die Massenmedien sind einflussreich.', tr:'Kitle iletişim araçları etkili.', type:'cümle', topic:'Toplum', subTopic:'Medya', cefr:'B2.1' },
      { de:'Der Klimawandel ist real.', tr:'İklim değişikliği gerçek.', type:'cümle', topic:'Çevre', subTopic:'İklim değişikliği', cefr:'B2.1' },
      { de:'Wir müssen unseren CO2-Fußabdruck reduzieren.', tr:'Karbon ayak izini azaltmalıyız.', type:'cümle', topic:'Çevre', subTopic:'Karbon', cefr:'B2.1' },
      { de:'Erneuerbare Energien werden verbreiteter.', tr:'Yenilenebilir enerji yaygınlaşıyor.', type:'cümle', topic:'Çevre', subTopic:'Enerji', cefr:'B2.1' },
      { de:'Die Plastikverschmutzung ist ein großes Problem.', tr:'Plastik kirliliği büyük sorun.', type:'cümle', topic:'Çevre', subTopic:'Plastik', cefr:'B2.1' },
      { de:'Die Wälder verschwinden.', tr:'Ormanlar yok oluyor.', type:'cümle', topic:'Çevre', subTopic:'Orman', cefr:'B2.1' },
      { de:'Nachhaltige Entwicklung ist erforderlich.', tr:'Sürdürülebilir kalkınma şart.', type:'cümle', topic:'Çevre', subTopic:'Kalkınma', cefr:'B2.1' },
      { de:'Die Recyclingquote ist niedrig.', tr:'Geri dönüşüm oranı düşük.', type:'cümle', topic:'Çevre', subTopic:'Geri dönüşüm', cefr:'B2.1' },
      { de:'Die Luftqualität verschlechtert sich.', tr:'Hava kalitesi bozuluyor.', type:'cümle', topic:'Çevre', subTopic:'Hava', cefr:'B2.1' },
      { de:'Das Umweltbewusstsein muss steigen.', tr:'Çevre bilinci artmalı.', type:'cümle', topic:'Çevre', subTopic:'Bilinç', cefr:'B2.1' },
      { de:'Die wirtschaftliche Stagnation ist besorgniserregend.', tr:'Ekonomik durgunluk endişe verici.', type:'cümle', topic:'Ekonomi', subTopic:'Durgunluk', cefr:'B2.1' },
      { de:'Die Inflationsrate ist gestiegen.', tr:'Enflasyon oranı yükseldi.', type:'cümle', topic:'Ekonomi', subTopic:'Enflasyon', cefr:'B2.1' },
      { de:'Die Arbeitslosenquote ist gesunken.', tr:'İşsizlik oranı düştü.', type:'cümle', topic:'Ekonomi', subTopic:'İşsizlik', cefr:'B2.1' },
      { de:'Der Wechselkurs schwankt.', tr:'Döviz kuru dalgalanıyor.', type:'cümle', topic:'Ekonomi', subTopic:'Döviz', cefr:'B2.1' },
      { de:'Die Aktien haben an Wert verloren.', tr:'Hisse senetleri değer kaybetti.', type:'cümle', topic:'Ekonomi', subTopic:'Borsa', cefr:'B2.1' },
      { de:'Die Marktbedingungen sind unsicher.', tr:'Piyasa koşulları belirsiz.', type:'cümle', topic:'Ekonomi', subTopic:'Piyasa', cefr:'B2.1' },
      { de:'Das Verbrauchervertrauen hat abgenommen.', tr:'Tüketici güveni azaldı.', type:'cümle', topic:'Ekonomi', subTopic:'Tüketici', cefr:'B2.1' },
      { de:'Es ist riskant zu investieren.', tr:'Yatırım yapmak riskli.', type:'cümle', topic:'Ekonomi', subTopic:'Yatırım', cefr:'B2.1' },
      { de:'Die Kreditzinsen sind gestiegen.', tr:'Kredi faizleri yükseldi.', type:'cümle', topic:'Ekonomi', subTopic:'Kredi', cefr:'B2.1' },
      { de:'Die Immobilienpreise sind gestiegen.', tr:'Gayrimenkul fiyatları arttı.', type:'cümle', topic:'Ekonomi', subTopic:'Gayrimenkul', cefr:'B2.1' },
      { de:'Die technologischen Entwicklungen sind rasant.', tr:'Teknolojik gelişmeler hızlı.', type:'cümle', topic:'Teknoloji', subTopic:'Gelişme', cefr:'B2.1' },
      { de:'Die digitale Transformation ist zwingend.', tr:'Dijital dönüşüm zorunlu.', type:'cümle', topic:'Teknoloji', subTopic:'Dönüşüm', cefr:'B2.1' },
      { de:'Die Datensicherheit ist wichtig.', tr:'Veri güvenliği önemli.', type:'cümle', topic:'Teknoloji', subTopic:'Güvenlik', cefr:'B2.1' },
      { de:'Künstliche Intelligenz verändert Arbeitsplätze.', tr:'Yapay zeka işleri değiştiriyor.', type:'cümle', topic:'Teknoloji', subTopic:'Yapay zeka', cefr:'B2.1' },
      { de:'Es besteht ein Automatisierungsrisiko.', tr:'Otomasyon riski var.', type:'cümle', topic:'Teknoloji', subTopic:'Otomasyon', cefr:'B2.1' },
      { de:'Die Internetverbindung ist langsam.', tr:'İnternet bağlantısı yavaş.', type:'cümle', topic:'Teknoloji', subTopic:'İnternet', cefr:'B2.1' },
      { de:'Ein Software-Update ist nötig.', tr:'Yazılım güncellemesi gerekli.', type:'cümle', topic:'Teknoloji', subTopic:'Yazılım', cefr:'B2.1' },
      { de:'Digitale Kompetenz ist erforderlich.', tr:'Dijital okuryazarlık şart.', type:'cümle', topic:'Teknoloji', subTopic:'Okuryazarlık', cefr:'B2.1' },
      { de:'Die Technologieabhängigkeit nimmt zu.', tr:'Teknoloji bağımlılığı artıyor.', type:'cümle', topic:'Teknoloji', subTopic:'Bağımlılık', cefr:'B2.1' },
      { de:'Virtuelle Realität wird verbreiteter.', tr:'Sanal gerçeklik yaygınlaşıyor.', type:'cümle', topic:'Teknoloji', subTopic:'VR', cefr:'B2.1' }
    ]
  },

  /* ═══ B2.2 ════════════════════════════════════════════════════════════════ */
  b22: {
    harfler: [],
    rakamlar: [],
    kelimeler: [
      { de:'die Konsequenz', tr:'sonuç / yaptırım', phonetic:'[kɔnzeˈkvɛnts]', article:'die' },
      { de:'der Sachverhalt', tr:'durum / olgu', phonetic:'[ˈzaxfɛɐhalt]', article:'der' },
      { de:'die Gegebenheit', tr:'gerçeklik / olgu', phonetic:'[ɡeˈɡeːbənhaɪt]', article:'die' },
      { de:'das Ausmaß', tr:'boyut / ölçü', phonetic:'[ˈaʊsmaːs]', article:'das' },
      { de:'die Einschränkung', tr:'kısıtlama', phonetic:'[ˈaɪnʃʁɛŋkʊŋ]', article:'die' },
      { de:'die Schlussfolgerung', tr:'çıkarım / sonuç', phonetic:'[ˈʃlʊsfɔlɡəʁʊŋ]', article:'die' },
      { de:'die Abweichung', tr:'sapma / farklılık', phonetic:'[ˈapvaɪçʊŋ]', article:'die' },
      { de:'beeinflussen', tr:'etkilemek', phonetic:'[bəˈaɪnflʊsən]' },
      { de:'sich durchsetzen', tr:'kendini kabul ettirmek', phonetic:'[zɪç ˈdʊʁçzɛtsən]' },
      { de:'hinterfragen', tr:'sorgulamak', phonetic:'[ˈhɪntɐfʁaːɡən]' },
      { de:'widerlegen', tr:'çürütmek', phonetic:'[ˈviːdɐleːɡən]' },
      { de:'begründen', tr:'gerekçelendirmek', phonetic:'[bəˈɡʁʏndən]' },
      { de:'einschränken', tr:'kısıtlamak', phonetic:'[ˈaɪnʃʁɛŋkən]' },
      { de:'unterliegen', tr:'tabi olmak', phonetic:'[ʊntɐˈliːɡən]' },
      { de:'sich abzeichnen', tr:'belirginleşmek', phonetic:'[zɪç ˈaptsaɪçnən]' }
    ],
    cumleler: [
      { de:'Ich bezweifle die Durchführbarkeit des Projekts.', tr:'Projenin uygulanabilirliğinden şüpheliyim.', type:'cümle', topic:'İş', subTopic:'Şüphe', cefr:'B2.2' },
      { de:'Es wurde keine Risikoanalyse durchgeführt.', tr:'Risk analizi yapılmadı.', type:'cümle', topic:'İş', subTopic:'Risk', cefr:'B2.2' },
      { de:'Unser Wettbewerbsvorteil schwindet.', tr:'Rekabet avantajımız azalıyor.', type:'cümle', topic:'İş', subTopic:'Rekabet', cefr:'B2.2' },
      { de:'Wir sollten neue Märkte erschließen.', tr:'Yeni pazarlara açılmalıyız.', type:'cümle', topic:'İş', subTopic:'Büyüme', cefr:'B2.2' },
      { de:'Es müssen dringend Maßnahmen ergriffen werden.', tr:'Acil önlem alınmalı.', type:'cümle', topic:'İş', subTopic:'Acil durum', cefr:'B2.2' },
      { de:'Das Unternehmen ist insolvent gegangen.', tr:'Şirket iflas etti.', type:'cümle', topic:'İş', subTopic:'İflas', cefr:'B2.2' },
      { de:'Die Restrukturierung wurde eingeleitet.', tr:'Yeniden yapılandırma başlatıldı.', type:'cümle', topic:'İş', subTopic:'Yeniden yapılanma', cefr:'B2.2' },
      { de:'Die Unternehmenskultur ist sehr wettbewerbsorientiert.', tr:'Şirket kültürü çok rekabetçi.', type:'cümle', topic:'İş', subTopic:'Şirket kültürü', cefr:'B2.2' },
      { de:'Meine Problemlösungsfähigkeit ist stark ausgeprägt.', tr:'Problem çözme yeteneğim güçlü.', type:'cümle', topic:'İş', subTopic:'Problem çözme', cefr:'B2.2' },
      { de:'Die Wohnungskrise verschärft sich.', tr:'Konut krizi derinleşiyor.', type:'cümle', topic:'Toplum', subTopic:'Konut', cefr:'B2.2' },
      { de:'Die Integration von Migranten wird schwieriger.', tr:'Göçmen entegrasyonu zorlaşıyor.', type:'cümle', topic:'Toplum', subTopic:'Entegrasyon', cefr:'B2.2' },
      { de:'Die Urbanisierung beschleunigt sich.', tr:'Kentsel dönüşüm hızlanıyor.', type:'cümle', topic:'Toplum', subTopic:'Kentsel dönüşüm', cefr:'B2.2' },
      { de:'Chancengleichheit muss gewährleistet werden.', tr:'Fırsat eşitliği sağlanmalı.', type:'cümle', topic:'Toplum', subTopic:'Eşitlik', cefr:'B2.2' },
      { de:'Desinformation verbreitet sich.', tr:'Dezenformasyon yayılıyor.', type:'cümle', topic:'Toplum', subTopic:'Dezenformasyon', cefr:'B2.2' },
      { de:'Die Sucht nach sozialen Medien nimmt zu.', tr:'Sosyal medya bağımlılığı artıyor.', type:'cümle', topic:'Toplum', subTopic:'Bağımlılık', cefr:'B2.2' },
      { de:'Die Biodiversität ist bedroht.', tr:'Biyoçeşitlilik tehdit altında.', type:'cümle', topic:'Çevre', subTopic:'Biyoçeşitlilik', cefr:'B2.2' },
      { de:'Die Wasserressourcen erschöpfen sich.', tr:'Su kaynakları tükeniyor.', type:'cümle', topic:'Çevre', subTopic:'Su', cefr:'B2.2' },
      { de:'Das Abfallmanagement muss verbessert werden.', tr:'Atık yönetimi iyileştirilmeli.', type:'cümle', topic:'Çevre', subTopic:'Atık', cefr:'B2.2' },
      { de:'Das Ökosystem-Gleichgewicht wurde gestört.', tr:'Ekosistem dengesi bozuldu.', type:'cümle', topic:'Çevre', subTopic:'Ekosistem', cefr:'B2.2' },
      { de:'In grüne Technologie sollte investiert werden.', tr:'Yeşil teknolojiye yatırım yapılmalı.', type:'cümle', topic:'Çevre', subTopic:'Teknoloji', cefr:'B2.2' },
      { de:'Natürliche Ressourcen müssen geschützt werden.', tr:'Doğal kaynaklar korunmalı.', type:'cümle', topic:'Çevre', subTopic:'Kaynaklar', cefr:'B2.2' }
    ]
  },


  /* ═══ C1.1 ════════════════════════════════════════════════════════════════ */
  c11: {
    harfler:  [],
    rakamlar: [],
    kelimeler: [
      { de:'die Ambiguität',  tr:'muğlaklık',               phonetic:'[ambɪɡuɪˈtɛːt]',   article:'die' },
      { de:'die Nuance',      tr:'nüans',                   phonetic:'[nuˈɑ̃ːsə]',         article:'die' },
      { de:'die Empathie',    tr:'empati',                  phonetic:'[ɛmpaˈtiː]',        article:'die' },
      { de:'die Resilienz',   tr:'psikolojik dayanıklılık', phonetic:'[ʁeˈzɪliɛnts]',    article:'die' },
      { de:'implizieren',     tr:'ima etmek',               phonetic:'[ɪmplɪˈtsiːʁən]' },
      { de:'widersprechen',   tr:'karşı çıkmak',            phonetic:'[ˈviːdɐˌʃpʁɛçən]' },
      { de:'analysieren',     tr:'analiz etmek',            phonetic:'[analyˈziːʁən]' },
      { de:'differenzieren',  tr:'farklılaştırmak',         phonetic:'[dɪfɛˈʁɛntsɪˌʁeːn]' }
    ],
    cumleler: [
      { de:'Trotz aller Fortschritte bleiben viele Fragen offen',   tr:'Tüm ilerlemelere rağmen pek çok soru yanıtsız kalmaktadır', phonetic:'[tʁoːts ˈalɐ ˈfɔʁtʃʁɪtə]',  type:'cümle' },
      { de:'Ich würde argumentieren, dass diese Maßnahme kontraproduktiv ist', tr:'Bu önlemin işe yaramaz olduğunu savunurum', phonetic:'[ɪç ˈvʏʁdə aʁɡumɛnˈtiːʁən]', type:'cümle' },
      // === veritabani.json — C1.1 (60 cümle) ===
      { de:'Diese Annahme erweist sich als spekulativ.', tr:'Bu varsayım spekülatif görünüyor.', type:'cümle', topic:'Akademik', subTopic:'Eleştiri', cefr:'C1.1' },
      { de:'Die Daten sind inkonsistent.', tr:'Veriler tutarsız.', type:'cümle', topic:'Akademik', subTopic:'Veri kalitesi', cefr:'C1.1' },
      { de:'Die Methodik ist fragwürdig.', tr:'Metodoloji sorgulanabilir.', type:'cümle', topic:'Akademik', subTopic:'Metodoloji', cefr:'C1.1' },
      { de:'Die Stichprobe ist nicht repräsentativ.', tr:'Örneklem temsili değil.', type:'cümle', topic:'Akademik', subTopic:'Örnekleme', cefr:'C1.1' },
      { de:'Die Rücklaufquote ist gering.', tr:'Yanıt oranı düşük.', type:'cümle', topic:'Akademik', subTopic:'Araştırma', cefr:'C1.1' },
      { de:'Die Interpretation bleibt subjektiv.', tr:'Yorum subjektif kalıyor.', type:'cümle', topic:'Akademik', subTopic:'Yorum', cefr:'C1.1' },
      { de:'Ein Interessenkonflikt liegt vor.', tr:'Çıkar çatışması mevcut.', type:'cümle', topic:'Akademik', subTopic:'Etik', cefr:'C1.1' },
      { de:'Die Quellenangaben sind unvollständig.', tr:'Kaynakça eksik.', type:'cümle', topic:'Akademik', subTopic:'Kaynakça', cefr:'C1.1' },
      { de:'Es liegt ein Plagiat vor.', tr:'İntihal yapılmış.', type:'cümle', topic:'Akademik', subTopic:'İntihal', cefr:'C1.1' },
      { de:'Es mangelt an Originalität.', tr:'Orijinallikten yoksun.', type:'cümle', topic:'Akademik', subTopic:'Orijinallik', cefr:'C1.1' },
      { de:'Ein oberflächlicher Ansatz.', tr:'Yüzeysel bir yaklaşım.', type:'cümle', topic:'Akademik', subTopic:'Eleştiri', cefr:'C1.1' },
      { de:'Die Literaturrecherche ist unzureichend.', tr:'Literatür taraması yetersiz.', type:'cümle', topic:'Akademik', subTopic:'Araştırma', cefr:'C1.1' },
      { de:'Der theoretische Rahmen ist unklar.', tr:'Teorik çerçeve belirsiz.', type:'cümle', topic:'Akademik', subTopic:'Teori', cefr:'C1.1' },
      { de:'Es fehlt an begrifflicher Klarheit.', tr:'Kavramsal açıklık yok.', type:'cümle', topic:'Akademik', subTopic:'Kavramlar', cefr:'C1.1' },
      { de:'Die Argumentation ist schwach.', tr:'Argümantasyon zayıf.', type:'cümle', topic:'Akademik', subTopic:'Mantık', cefr:'C1.1' },
      { de:'Die Schlussfolgerung ist fehlerhaft.', tr:'Çıkarım hatalı.', type:'cümle', topic:'Akademik', subTopic:'Mantık', cefr:'C1.1' },
      { de:'Ein dogmatischer Ansatz.', tr:'Kanlı ısrarcı bir yaklaşım.', type:'cümle', topic:'Akademik', subTopic:'Açık fikirlilik', cefr:'C1.1' },
      { de:'Es fehlt an interdisziplinärer Perspektive.', tr:'Disiplinler arası perspektif eksik.', type:'cümle', topic:'Akademik', subTopic:'Disiplinler arası', cefr:'C1.1' },
      { de:'Die Hypothese muss falsifizierbar sein.', tr:'Hipotez test edilebilir olmalı.', type:'cümle', topic:'Akademik', subTopic:'Hipotez', cefr:'C1.1' },
      { de:'Der Paradigmenwechsel ist unvermeidlich.', tr:'Paradigma değişimi kaçınılmaz.', type:'cümle', topic:'Akademik', subTopic:'Paradigma', cefr:'C1.1' },
      { de:'Der theoretische Rahmen bleibt unklar.', tr:'Teorik çerçeve belirsiz kalıyor.', type:'cümle', topic:'Akademik', subTopic:'Teori', cefr:'C1.1' },
      { de:'Die empirische Evidenz ist unzureichend.', tr:'Ampirik kanıt yetersiz.', type:'cümle', topic:'Akademik', subTopic:'Kanıt', cefr:'C1.1' },
      { de:'Die statistische Signifikanz ist hoch.', tr:'İstatistiksel anlamlılık yüksek.', type:'cümle', topic:'Akademik', subTopic:'İstatistik', cefr:'C1.1' },
      { de:'Das Konfidenzintervall ist eng.', tr:'Güven aralığı dar.', type:'cümle', topic:'Akademik', subTopic:'İstatistik', cefr:'C1.1' },
      { de:'Der p-Wert ist signifikant.', tr:'P-değeri anlamlı.', type:'cümle', topic:'Akademik', subTopic:'İstatistik', cefr:'C1.1' },
      { de:'Die Longitudinalstudie ist zeitaufwendig.', tr:'Longitudinal çalışma zaman alıcı.', type:'cümle', topic:'Akademik', subTopic:'Araştırma', cefr:'C1.1' },
      { de:'Die Querschnittsanalyse liefert begrenzte Informationen.', tr:'Kesitsel analiz sınırlı bilgi verir.', type:'cümle', topic:'Akademik', subTopic:'Analiz', cefr:'C1.1' },
      { de:'Die qualitative Forschung ist tiefgehend.', tr:'Nitel araştırma derinlemesine.', type:'cümle', topic:'Akademik', subTopic:'Araştırma', cefr:'C1.1' },
      { de:'Die quantitativen Daten sind objektiv.', tr:'Nicel veri objektif.', type:'cümle', topic:'Akademik', subTopic:'Veri', cefr:'C1.1' },
      { de:'Die Literaturrecherche ist umfassend.', tr:'Literatür taraması kapsamlı.', type:'cümle', topic:'Akademik', subTopic:'Literatür', cefr:'C1.1' },
      { de:'Die systematische Übersichtsarbeit ist erforderlich.', tr:'Sistematik derleme gerekli.', type:'cümle', topic:'Akademik', subTopic:'Derleme', cefr:'C1.1' },
      { de:'Das Datenschutzprotokoll wurde angewendet.', tr:'Gizlilik protokolü uygulandı.', type:'cümle', topic:'Akademik', subTopic:'Gizlilik', cefr:'C1.1' },
      { de:'Ein Publikationsbias liegt vor.', tr:'Yayın biası mevcut.', type:'cümle', topic:'Akademik', subTopic:'Bias', cefr:'C1.1' },
      { de:'Ein finanzieller Interessenkonflikt wurde gemeldet.', tr:'Finansal çıkar çatışması bildirildi.', type:'cümle', topic:'Akademik', subTopic:'Çıkar çatışması', cefr:'C1.1' },
      { de:'Ein Forschungsprotokoll wurde geführt.', tr:'Çalışma kaydı tutuldu.', type:'cümle', topic:'Akademik', subTopic:'Protokol', cefr:'C1.1' },
      { de:'Die Effektstärke ist gering.', tr:'Etki büyüklüğü küçük.', type:'cümle', topic:'Akademik', subTopic:'Etki', cefr:'C1.1' },
      { de:'Das deduktive Schließen ist gültig.', tr:'Dedüktif akıl yürütme geçerli.', type:'cümle', topic:'Felsefe', subTopic:'Mantık', cefr:'C1.1' },
      { de:'Die induktive Inferenz ist stark.', tr:'İndüktif çıkarım güçlü.', type:'cümle', topic:'Felsefe', subTopic:'Mantık', cefr:'C1.1' },
      { de:'Ein Induktionsfehler wurde begangen.', tr:'Tümevarım hatası yapıldı.', type:'cümle', topic:'Felsefe', subTopic:'Hata', cefr:'C1.1' },
      { de:'Eine falsche Dichotomie wurde aufgestellt.', tr:'Yanlış ikilem kuruldu.', type:'cümle', topic:'Felsefe', subTopic:'Hata', cefr:'C1.1' },
      { de:'Ein Zirkelschluss wurde verwendet.', tr:'Halka argümanı kullanıldı.', type:'cümle', topic:'Felsefe', subTopic:'Hata', cefr:'C1.1' },
      { de:'Der Appell an die Autorität ist ungültig.', tr:'Otoriteye başvuru geçersiz.', type:'cümle', topic:'Felsefe', subTopic:'Hata', cefr:'C1.1' },
      { de:'Die Slippery-Slope-Logik ist schwach.', tr:'Slippery slope mantığı zayıf.', type:'cümle', topic:'Felsefe', subTopic:'Hata', cefr:'C1.1' },
      { de:'Ein Strohmannargument wurde konstruiert.', tr:'Straw man argümanı kuruldu.', type:'cümle', topic:'Felsefe', subTopic:'Hata', cefr:'C1.1' },
      { de:'Ein Ad-hominem-Angriff wurde geführt.', tr:'Ad hominem saldırı yapıldı.', type:'cümle', topic:'Felsefe', subTopic:'Hata', cefr:'C1.1' },
      { de:'Ein Ablenkungsmanöver wurde eingesetzt.', tr:'Red herring kullanıldı.', type:'cümle', topic:'Felsefe', subTopic:'Hata', cefr:'C1.1' },
      { de:'Eine voreilige Verallgemeinerung wurde getroffen.', tr:'Hasty generalization yapıldı.', type:'cümle', topic:'Felsefe', subTopic:'Hata', cefr:'C1.1' },
      { de:'Die Sozialstruktur ist determinierend.', tr:'Sosyal yapı belirleyici.', type:'cümle', topic:'Sosyoloji', subTopic:'Yapı', cefr:'C1.1' },
      { de:'Die kulturellen Normen sind internalisiert.', tr:'Kültürel normlar içselleştirilmiş.', type:'cümle', topic:'Sosyoloji', subTopic:'Norm', cefr:'C1.1' },
      { de:'Ein Rollenkonflikt wird erlebt.', tr:'Rol çatışması yaşanıyor.', type:'cümle', topic:'Sosyoloji', subTopic:'Rol', cefr:'C1.1' },
      { de:'Die Statussymbole haben sich verändert.', tr:'Statü sembolleri değişti.', type:'cümle', topic:'Sosyoloji', subTopic:'Statü', cefr:'C1.1' },
      { de:'Der Demokratisierungsprozess ist langsam.', tr:'Demokratikleşme süreci yavaş.', type:'cümle', topic:'Siyaset', subTopic:'Demokrasi', cefr:'C1.1' },
      { de:'Die Zivilgesellschaft stärkt sich.', tr:'Sivil toplum güçleniyor.', type:'cümle', topic:'Siyaset', subTopic:'Sivil toplum', cefr:'C1.1' },
      { de:'Der öffentliche Druck hat zugenommen.', tr:'Kamuoyu baskısı arttı.', type:'cümle', topic:'Siyaset', subTopic:'Kamuoyu', cefr:'C1.1' },
      { de:'Die politische Strategie hat sich geändert.', tr:'Politik strateji değişti.', type:'cümle', topic:'Siyaset', subTopic:'Strateji', cefr:'C1.1' },
      { de:'Die ideologischen Unterschiede sind ausgeprägt.', tr:'İdeolojik farklar belirgin.', type:'cümle', topic:'Siyaset', subTopic:'İdeoloji', cefr:'C1.1' },
      { de:'Wissenschaftlicher Konsens wurde erreicht.', tr:'Bilimsel konsensüs sağlandı.', type:'cümle', topic:'Akademik', subTopic:'Konsens', cefr:'C1.1' },
      { de:'Das Forschungsparadigma hat sich gewandelt.', tr:'Araştırma paradigması değişti.', type:'cümle', topic:'Akademik', subTopic:'Paradigma', cefr:'C1.1' },
      { de:'Ein interdisziplinärer Ansatz ist zwingend.', tr:'Disiplinler arası yaklaşım zorunlu.', type:'cümle', topic:'Akademik', subTopic:'Disiplinler arası', cefr:'C1.1' },
      { de:'Der Wissensgesellschaftswandel ist abgeschlossen.', tr:'Bilgi toplumu dönüşümü tamamlandı.', type:'cümle', topic:'Toplum', subTopic:'Bilgi toplumu', cefr:'C1.1' }
    ]
  },

  /* ═══ C1.2 ════════════════════════════════════════════════════════════════ */
  c12: {
    harfler:  [],
    rakamlar: [],
    kelimeler: [
      { de:'die Nachhaltigkeit', tr:'sürdürülebilirlik',                phonetic:'[ˈnaːxˌhaltɪçkaɪt]', article:'die' },
      { de:'die Weltanschauung', tr:'dünya görüşü',                     phonetic:'[ˈvɛltˌanʃaʊʊŋ]',   article:'die' },
      { de:'das Heimweh',        tr:'sıla özlemi',                      phonetic:'[ˈhaɪmveː]',         article:'das' },
      { de:'die Schadenfreude',  tr:'başkasının mutsuzluğuna sevinme',  phonetic:'[ˈʃaːdənˌfʁɔɪdə]',  article:'die' },
      { de:'der Zeitgeist',      tr:'dönemin ruhu',                     phonetic:'[ˈtsaɪtˌɡaɪst]',    article:'der' },
      { de:'hinterfragen',       tr:'sorgulamak',                       phonetic:'[ˈhɪntɐˌfʁaːɡən]' },
      { de:'berücksichtigen',    tr:'göz önünde bulundurmak',           phonetic:'[bəˈʁʏkzɪçtɪɡən]' }
    ],
    cumleler: [
      { de:'Die Kunst liegt darin, die richtige Balance zwischen Theorie und Praxis zu finden', tr:'Asıl beceri, teori ile pratik arasında doğru dengeyi bulmaktadır', phonetic:'[diː kʊnst liːkt daˈʁɪn]', type:'cümle' },
      // === veritabani.json — C1.2 (39 cümle) ===
      { de:'Lassen sich die Ergebnisse generalisieren?', tr:'Sonuçlar genellenebilir mi?', type:'cümle', topic:'Akademik', subTopic:'Genellenebilirlik', cefr:'C1.2' },
      { de:'Es wird von der Objektivität abgewichen.', tr:'Objektiflikten uzaklaşılıyor.', type:'cümle', topic:'Akademik', subTopic:'Objektiflik', cefr:'C1.2' },
      { de:'Es wurde keine tiefgreifende Analyse durchgeführt.', tr:'Derinlemesine analiz edilmemiş.', type:'cümle', topic:'Akademik', subTopic:'Analiz derinliği', cefr:'C1.2' },
      { de:'Es konnte keine Kausalität nachgewiesen werden.', tr:'Nedensellik kurulamadı.', type:'cümle', topic:'Akademik', subTopic:'Nedensellik', cefr:'C1.2' },
      { de:'Korrelation wurde mit Kausalität verwechselt.', tr:'Korelasyon nedensellikle karıştırılmış.', type:'cümle', topic:'Akademik', subTopic:'İstatistik hatası', cefr:'C1.2' },
      { de:'Alternative Erklärungen wurden ausgeblendet.', tr:'Alternatif açıklamalar göz ardı edilmiş.', type:'cümle', topic:'Akademik', subTopic:'Tarafsızlık', cefr:'C1.2' },
      { de:'Es wurde keine kritische Distanz gewahrt.', tr:'Eleştirel mesafe korunmamış.', type:'cümle', topic:'Akademik', subTopic:'Objektiflik', cefr:'C1.2' },
      { de:'Voreingenommenheiten haben eine Rolle gespielt.', tr:'On yargılar etkili olmuş.', type:'cümle', topic:'Akademik', subTopic:'Önyargı', cefr:'C1.2' },
      { de:'Der kulturelle Kontext wurde nicht berücksichtigt.', tr:'Kültürel bağlam göz önünde bulundurulmamış.', type:'cümle', topic:'Akademik', subTopic:'Bağlam', cefr:'C1.2' },
      { de:'Der zeitliche Kontext wurde vernachlässigt.', tr:'Zamansal bağlam ihmal edilmiş.', type:'cümle', topic:'Akademik', subTopic:'Tarihsel bağlam', cefr:'C1.2' },
      { de:'Die epistemologische Grundlage muss hinterfragt werden.', tr:'Epistemolojik temel sorgulanmalı.', type:'cümle', topic:'Akademik', subTopic:'Epistemoloji', cefr:'C1.2' },
      { de:'Die ontologische Prämisse ist nicht explizit.', tr:'Ontolojik varsayım açık değil.', type:'cümle', topic:'Akademik', subTopic:'Ontoloji', cefr:'C1.2' },
      { de:'Die methodologische Konsistenz wurde gewährleistet.', tr:'Metodolojik tutarlılık sağlanmış.', type:'cümle', topic:'Akademik', subTopic:'Metodoloji', cefr:'C1.2' },
      { de:'Die Meta-Analyse ist synthetisierend.', tr:'Meta-analiz birleştirici.', type:'cümle', topic:'Akademik', subTopic:'Meta-analiz', cefr:'C1.2' },
      { de:'Die Ethikkommissionsgenehmigung wurde eingeholt.', tr:'Etik kurul onayı alındı.', type:'cümle', topic:'Akademik', subTopic:'Etik', cefr:'C1.2' },
      { de:'Das informierte Einverständnis wurde unterschrieben.', tr:'Aydınlatılmış onam formu imzalandı.', type:'cümle', topic:'Akademik', subTopic:'Onam', cefr:'C1.2' },
      { de:'Eine Replikationsstudie sollte durchgeführt werden.', tr:'Replikasyon çalışması yapılmalı.', type:'cümle', topic:'Akademik', subTopic:'Replikasyon', cefr:'C1.2' },
      { de:'Die Abduktion ist die beste Erklärung.', tr:'Abdüksiyon en iyi açıklama.', type:'cümle', topic:'Felsefe', subTopic:'Mantık', cefr:'C1.2' },
      { de:'Es liegt eine Bestätigungsverzerrung vor.', tr:'Doğrulamacı önyargı var.', type:'cümle', topic:'Felsefe', subTopic:'Önyargı', cefr:'C1.2' },
      { de:'Ein Argumentum ad populum wurde gemacht.', tr:'Kısaca argümanı yapıldı.', type:'cümle', topic:'Felsefe', subTopic:'Hata', cefr:'C1.2' },
      { de:'Ein genetischer Fehlschluss wurde begangen.', tr:'Genetik düşünce hatası yapıldı.', type:'cümle', topic:'Felsefe', subTopic:'Hata', cefr:'C1.2' },
      { de:'Das Sozialkapital ist akkumuliert.', tr:'Sosyal sermaye birikmiş.', type:'cümle', topic:'Sosyoloji', subTopic:'Sermaye', cefr:'C1.2' },
      { de:'Das Kulturkapital wurde tradiert.', tr:'Kültürel sermaye aktarılmış.', type:'cümle', topic:'Sosyoloji', subTopic:'Sermaye', cefr:'C1.2' },
      { de:'Symbolische Gewalt liegt vor.', tr:'Simgesel şiddet mevcut.', type:'cümle', topic:'Sosyoloji', subTopic:'Şiddet', cefr:'C1.2' },
      { de:'Der Habitus ist strukturierend.', tr:'Habitus yapılandırıcı.', type:'cümle', topic:'Sosyoloji', subTopic:'Habitus', cefr:'C1.2' },
      { de:'Die Feldtheorie wurde angewandt.', tr:'Alan teorisi uygulandı.', type:'cümle', topic:'Sosyoloji', subTopic:'Teori', cefr:'C1.2' },
      { de:'Entfremdung wird empfunden.', tr:'Yabancılaşma hissediliyor.', type:'cümle', topic:'Sosyoloji', subTopic:'Yabancılaşma', cefr:'C1.2' },
      { de:'Die Bürokratierationalität ist verbreitet.', tr:'Bürokrasi rasyonalitesi yaygın.', type:'cümle', topic:'Sosyoloji', subTopic:'Bürokrasi', cefr:'C1.2' },
      { de:'Die protestantische Ethik ist einflussreich.', tr:'Protestan ahlakı etkili.', type:'cümle', topic:'Sosyoloji', subTopic:'Ahlak', cefr:'C1.2' },
      { de:'Der Hegemoniekampf dauert an.', tr:'Hegemonya mücadelesi sürüyor.', type:'cümle', topic:'Siyaset', subTopic:'Hegemonya', cefr:'C1.2' },
      { de:'Die ideologischen Staatsapparate sind funktional.', tr:'İdeolojik devlet aygıtları işlevsel.', type:'cümle', topic:'Siyaset', subTopic:'Devlet', cefr:'C1.2' },
      { de:'Die Souveränitätskrisen verschärfen sich.', tr:'Egemenlik krizleri derinleşiyor.', type:'cümle', topic:'Siyaset', subTopic:'Egemenlik', cefr:'C1.2' },
      { de:'Die Biomachttechniken sind weitverbreitet.', tr:'Biyoiktidar teknikleri yaygın.', type:'cümle', topic:'Siyaset', subTopic:'İktidar', cefr:'C1.2' },
      { de:'Die Disziplinarmechanismen funktionieren.', tr:'Disiplin mekanizmaları işliyor.', type:'cümle', topic:'Siyaset', subTopic:'Disiplin', cefr:'C1.2' },
      { de:'Das Panoptikummodell ist gültig.', tr:'Panoptikon modeli geçerli.', type:'cümle', topic:'Siyaset', subTopic:'Panoptikon', cefr:'C1.2' },
      { de:'Die normative Struktur ist verinnerlicht.', tr:'Normatif yapı içselleştirilmiş.', type:'cümle', topic:'Sosyoloji', subTopic:'Norm', cefr:'C1.2' },
      { de:'Eine epistemische Gemeinschaft hat sich gebildet.', tr:'Epistemic topluluk oluşmuş.', type:'cümle', topic:'Akademik', subTopic:'Topluluk', cefr:'C1.2' },
      { de:'Methodologischer Pluralismus wurde adoptiert.', tr:'Metodolojik çoğulculuk benimsendi.', type:'cümle', topic:'Akademik', subTopic:'Çoğulculuk', cefr:'C1.2' },
      { de:'Transdisziplinäres Wissen wurde produziert.', tr:'Transdisipliner bilgi üretildi.', type:'cümle', topic:'Akademik', subTopic:'Bilgi', cefr:'C1.2' }
    ]
  },

  /* ═══ C2.1 ════════════════════════════════════════════════════════════════ */
  c21: {
    harfler:  [],
    rakamlar: [],
    kelimeler: [
      { de:'die Akribie',          tr:'titizlik / hassaslık',     phonetic:'[akʁiˈbiː]',             article:'die' },
      { de:'die Gleichgültigkeit', tr:'ilgisizlik / kayıtsızlık', phonetic:'[ˈɡlaɪçˌɡʏltɪçkaɪt]',  article:'die' },
      { de:'das Aufbegehren',      tr:'isyan / başkaldırı',       phonetic:'[ˈaʊfbəˌɡeːʁən]',       article:'das' },
      { de:'verfeinern',           tr:'rafine etmek',             phonetic:'[fɛɐˈfaɪnɐn]' },
      { de:'entlarven',            tr:'ifşa etmek',               phonetic:'[ɛntˈlaʁfən]' },
      { de:'in Frage stellen',     tr:'sorgulamak',               phonetic:'[ɪn ˈfʁaːɡə ˈʃtɛlən]' }
    ],
    cumleler: [
      { de:'Es wäre verfehlt, diese Entwicklung auf einen einzigen Faktor zurückzuführen', tr:'Bu gelişmeyi tek bir faktöre bağlamak hatalı olur',          phonetic:'[ɛs ˈvɛːʁə fɛɐˈfeːlt]', type:'cümle' },
      { de:'Man muss das Ganze im Kontext betrachten',                                     tr:'Bütünü bağlamı içinde değerlendirmek gerekir',                phonetic:'[man mʊs das ˈɡantsə]',  type:'cümle' },
      // === veritabani.json — C21 (57 cümle) ===
      { de:'Die polysemische Struktur des Textes muss berücksichtigt werden.', tr:'Metnin polisemik yapısı dikkate alınmalı.', type:'cümle', topic:'Edebi analiz', subTopic:'Çokanlamlılık', cefr:'C2.1' },
      { de:'Eine ironische Lesart kann nicht ausgeschlossen werden.', tr:'İronik alımlama göz ardı edilemez.', type:'cümle', topic:'Edebi analiz', subTopic:'İroni', cefr:'C2.1' },
      { de:'Die metaphorische Dichte erschwert den Textzugang.', tr:'Metaforik yoğunluk metni zorlaştırıyor.', type:'cümle', topic:'Edebi analiz', subTopic:'Metafor', cefr:'C2.1' },
      { de:'Die Intertextualität ist unübersehbar.', tr:'İntertekstüalite açıkça belirgin.', type:'cümle', topic:'Edebi analiz', subTopic:'İntertekstüalite', cefr:'C2.1' },
      { de:'Autokritische Elemente sind vorhanden.', tr:'Otokritik unsurlar mevcut.', type:'cümle', topic:'Edebi analiz', subTopic:'Öz-eleştiri', cefr:'C2.1' },
      { de:'Eine dekonstruktivistische Lesart ist möglich.', tr:'Dekonstrüktivist bir okuma yapılabilir.', type:'cümle', topic:'Edebi analiz', subTopic:'Dekonstrüksiyon', cefr:'C2.1' },
      { de:'Eine feministische Kritikperspektive ist anwendbar.', tr:'Feminist eleştiri perspektifi uygulanabilir.', type:'cümle', topic:'Edebi analiz', subTopic:'Feminist eleştiri', cefr:'C2.1' },
      { de:'Eine postkoloniale Lesart ist zwingend.', tr:'Post-kolonyal okuma zorunlu.', type:'cümle', topic:'Edebi analiz', subTopic:'Post-kolonyalizm', cefr:'C2.1' },
      { de:'Eine psychoanalytische Deutung liefert Mehrwert.', tr:'Psikanalitik yorum katma değer sağlar.', type:'cümle', topic:'Edebi analiz', subTopic:'Psikanaliz', cefr:'C2.1' },
      { de:'Eine marxistische Analyse offenbart strukturelle Widersprüche.', tr:'Marksist analiz yapısal çelişkileri ortaya çıkarır.', type:'cümle', topic:'Edebi analiz', subTopic:'Marksizm', cefr:'C2.1' },
      { de:'Die Digital Humanities erfordern neue Methodologien.', tr:'Dijital beşerî bilimler yeni metodolojiler gerektirir.', type:'cümle', topic:'Akademik', subTopic:'Dijital beşerî bilimler', cefr:'C2.1' },
      { de:'Die Effizienz der Remote-Arbeit ist diskursiv geworden.', tr:'Uzaktan çalışma verimliliği tartışmalı hale geldi.', type:'cümle', topic:'İş', subTopic:'Uzaktan çalışma', cefr:'C2.1' },
      { de:'KI-Ethik ist ein Dringlichkeitsthema.', tr:'Yapay zeka etiği acil bir mesele.', type:'cümle', topic:'Teknoloji', subTopic:'Yapay zeka', cefr:'C2.1' },
      { de:'Datensouveränität ist ein geopolitischer Ertrag.', tr:'Veri egemenliği jeo-politik bir kazanım.', type:'cümle', topic:'Teknoloji', subTopic:'Veri', cefr:'C2.1' },
      { de:'Cybersicherheit ist integraler Bestandteil der nationalen Sicherheit.', tr:'Siber güvenlik ulusal güvenliğin ayrılmaz parçası.', type:'cümle', topic:'Güvenlik', subTopic:'Siber güvenlik', cefr:'C2.1' },
      { de:'Die Klimaanpassung ist kostspielig, aber unvermeidlich.', tr:'İklim değişikliği adaptasyonu maliyetli ama kaçınılmaz.', type:'cümle', topic:'Çevre', subTopic:'İklim değişikliği', cefr:'C2.1' },
      { de:'Soziale Gerechtigkeit ist Prämissen nachhaltiger Entwicklung.', tr:'Sosyal adalet sürdürülebilir kalkınmanın ön koşulu.', type:'cümle', topic:'Toplum', subTopic:'Sosyal adalet', cefr:'C2.1' },
      { de:'Die Intertextualität ist evident.', tr:'Metinlerarasılık belirgin.', type:'cümle', topic:'Edebi analiz', subTopic:'İntertekstüalite', cefr:'C2.1' },
      { de:'Die Heteroglossia-Struktur ist komplex.', tr:'Heteroglossia yapısı karmaşık.', type:'cümle', topic:'Edebi analiz', subTopic:'Heteroglossia', cefr:'C2.1' },
      { de:'Die karnevalesken Elemente sind dominant.', tr:'Karnivalesque öğeler baskın.', type:'cümle', topic:'Edebi analiz', subTopic:'Karnaval', cefr:'C2.1' },
      { de:'Die Chronotop-Analyse ist erforderlich.', tr:'Chronotop analizi gerekli.', type:'cümle', topic:'Edebi analiz', subTopic:'Chronotop', cefr:'C2.1' },
      { de:'Analepsis und Prolepsis wurden verwendet.', tr:'Analepsis ve prolepsis kullanılmış.', type:'cümle', topic:'Edebi analiz', subTopic:'Zaman', cefr:'C2.1' },
      { de:'Die Fokalisation ist variabel.', tr:'Fokalizasyon değişken.', type:'cümle', topic:'Edebi analiz', subTopic:'Fokalizasyon', cefr:'C2.1' },
      { de:'Die narratologische Analyse ist tiefgehend.', tr:'Narratolojik analiz derinlemesine.', type:'cümle', topic:'Edebi analiz', subTopic:'Naratoloji', cefr:'C2.1' },
      { de:'Ein semiotischer Ansatz ist anwendbar.', tr:'Göstergebilimsel yaklaşım uygulanabilir.', type:'cümle', topic:'Edebi analiz', subTopic:'Göstergebilim', cefr:'C2.1' },
      { de:'Die Diskursanalyse ist vielschichtig.', tr:'Söylem analizi çok katmanlı.', type:'cümle', topic:'Edebi analiz', subTopic:'Söylem', cefr:'C2.1' },
      { de:'Archetypische Bilder wiederholen sich.', tr:'Arketipsel imgeler tekrarlanıyor.', type:'cümle', topic:'Edebi analiz', subTopic:'Arketip', cefr:'C2.1' },
      { de:'Mythologische Allusionen sind häufig.', tr:'Mitolojik alüzyonlar sık.', type:'cümle', topic:'Edebi analiz', subTopic:'Mitoloji', cefr:'C2.1' },
      { de:'Die modernistische Ästhetik ist ausgeprägt.', tr:'Modernist estetik belirgin.', type:'cümle', topic:'Edebi analiz', subTopic:'Modernizm', cefr:'C2.1' },
      { de:'Die postmoderne Ironie ist dominant.', tr:'Postmodern ironi baskın.', type:'cümle', topic:'Edebi analiz', subTopic:'Postmodernizm', cefr:'C2.1' },
      { de:'Die metafiktionalen Elemente sind auffällig.', tr:'Metafictional unsurlar dikkat çekici.', type:'cümle', topic:'Edebi analiz', subTopic:'Metafiction', cefr:'C2.1' },
      { de:'Der ontologische Unterschied ist fundamental.', tr:'Ontolojik farklılık temel.', type:'cümle', topic:'Felsefe', subTopic:'Ontoloji', cefr:'C2.1' },
      { de:'Die Daseinsanalyse ist erforderlich.', tr:'Dasein analizi gerekli.', type:'cümle', topic:'Felsefe', subTopic:'Dasein', cefr:'C2.1' },
      { de:'Die Wirkungsgeschichte ist bestimmend.', tr:'Etki tarihçesi belirleyici.', type:'cümle', topic:'Felsefe', subTopic:'Etki', cefr:'C2.1' },
      { de:'Die Diskurspraktiken sind formend.', tr:'Söylem pratikleri şekillendirici.', type:'cümle', topic:'Felsefe', subTopic:'Söylem', cefr:'C2.1' },
      { de:'Das Nomadismus-Konzept ist produktiv.', tr:'Nomadizm kavramı üretken.', type:'cümle', topic:'Felsefe', subTopic:'Nomadizm', cefr:'C2.1' },
      { de:'Der Oberflächeneffekt ist tiefgehend.', tr:'Yüzey etkisi derinlemesine.', type:'cümle', topic:'Felsefe', subTopic:'Yüzey', cefr:'C2.1' },
      { de:'Die Performativitätstheorie ist erklärend.', tr:'Performativite kuramı açıklayıcı.', type:'cümle', topic:'Felsefe', subTopic:'Performativite', cefr:'C2.1' },
      { de:'Die Gender-Konstruktion wird iteriert.', tr:'Cinsiyet inşası tekrarlanıyor.', type:'cümle', topic:'Felsefe', subTopic:'Cinsiyet', cefr:'C2.1' },
      { de:'Der kulturelle Imperialismus ist evident.', tr:'Kültürel emperyalizm belirgin.', type:'cümle', topic:'Kültür', subTopic:'Emperyalizm', cefr:'C2.1' },
      { de:'Der orientalische Diskurs ist konstruktiv.', tr:'Oryantalist söylem yapılandırıcı.', type:'cümle', topic:'Kültür', subTopic:'Oryantalizm', cefr:'C2.1' },
      { de:'Die Dependenztheorie ist gültig.', tr:'Eşitsiz gelişme teorisi geçerli.', type:'cümle', topic:'Kültür', subTopic:'Bağımlılık', cefr:'C2.1' },
      { de:'Das Zentrum-Peripherie-Verhältnis ist asymmetrisch.', tr:'Merkez-çevre ilişkisi asimetrik.', type:'cümle', topic:'Kültür', subTopic:'Merkez-çevre', cefr:'C2.1' },
      { de:'Die kulturelle Hegemonie wird aufrechterhalten.', tr:'Kültürel hegemonya sürdürülüyor.', type:'cümle', topic:'Kültür', subTopic:'Hegemonya', cefr:'C2.1' },
      { de:'Der Subkulturwiderstand ist symbolisch.', tr:'Altkültür direnişi sembolik.', type:'cümle', topic:'Kültür', subTopic:'Altkültür', cefr:'C2.1' },
      { de:'Der Kodierungs- und Dekodierungsprozess ist komplex.', tr:'Kodlama ve kod çözme süreci karmaşık.', type:'cümle', topic:'Medya', subTopic:'Kodlama', cefr:'C2.1' },
      { de:'Die Repräsentationspraktiken sind konstruktiv.', tr:'Temsil pratikleri inşacı.', type:'cümle', topic:'Medya', subTopic:'Temsil', cefr:'C2.1' },
      { de:'Die Medientexte sind polysem.', tr:'Medya metinleri çok anlamlı.', type:'cümle', topic:'Medya', subTopic:'Metin', cefr:'C2.1' },
      { de:'Die Konsumkulturhegemonie ist total.', tr:'Tüketim kültürü hegemonyası tam.', type:'cümle', topic:'Kültür', subTopic:'Tüketim', cefr:'C2.1' },
      { de:'Die Markenidentität ist internalisiert.', tr:'Marka kimliği içselleştirilmiş.', type:'cümle', topic:'Kültür', subTopic:'Marka', cefr:'C2.1' },
      { de:'Die Globalisierungskritik ist berechtigt.', tr:'Küreselleşme eleştirisi geçerli.', type:'cümle', topic:'Kültür', subTopic:'Küreselleşme', cefr:'C2.1' },
      { de:'Die transkulturellen Flüsse sind intensiv.', tr:'Transkültürel akışlar yoğun.', type:'cümle', topic:'Kültür', subTopic:'Transkültürel', cefr:'C2.1' },
      { de:'Die diasporische Identität ist hybrid.', tr:'Diasporik kimlik hibrit.', type:'cümle', topic:'Kültür', subTopic:'Diaspora', cefr:'C2.1' },
      { de:'Der kulturelle Gedächtnistransfer ist kontinuierlich.', tr:'Kültürel bellek aktarımı sürekli.', type:'cümle', topic:'Kültür', subTopic:'Bellek', cefr:'C2.1' },
      { de:'Die Geschlechterperformance wird iteriert.', tr:'Toplumsal cinsiyet performansı tekrarlanıyor.', type:'cümle', topic:'Kültür', subTopic:'Cinsiyet', cefr:'C2.1' },
      { de:'Die Queer-Theorie destabilisiert Normativität.', tr:'Queer teori normativiteyi bozuyor.', type:'cümle', topic:'Kültür', subTopic:'Queer', cefr:'C2.1' },
      { de:'Die postkoloniale Kritik eröffnet Einsichten.', tr:'Post-kolonyal eleştiri açılım sağlıyor.', type:'cümle', topic:'Kültür', subTopic:'Post-kolonyal', cefr:'C2.1' }
    ]
  },

  /* ═══ C2.2 ════════════════════════════════════════════════════════════════ */
  c22: {
    harfler:  [],
    rakamlar: [],
    kelimeler: [],
    cumleler: [
      { de:'Ohne Fleiß kein Preis',                 tr:'Emeksiz yemek olmaz',                              phonetic:'[ˈoːnə flaɪs kaɪn pʁaɪs]',   type:'deyim' },
      { de:'Aller Anfang ist schwer',               tr:'Her başlangıç zordur',                             phonetic:'[ˈalɐ ˈanfaŋ ɪst ʃveːɐ]',     type:'deyim' },
      { de:'Übung macht den Meister',               tr:'İnsan ustalığı pratikle kazanır',                  phonetic:'[ˈyːbʊŋ maxt deːn ˈmaɪstɐ]',  type:'deyim' },
      { de:'Der Apfel fällt nicht weit vom Stamm',  tr:'Elma ağacın dibine düşer',                        phonetic:'[deːɐ ˈapfəl fɛlt nɪçt vaɪt]', type:'deyim' },
      { de:'Morgenstund hat Gold im Mund',          tr:'Erken kalkan yol alır',                            phonetic:'[ˈmɔʁɡənʃtʊnt hat ɡɔlt]',      type:'deyim' },
      { de:'Ende gut, alles gut',                   tr:'Son gülen iyi güler',                              phonetic:'[ˈɛndə ɡuːt ˈalɐs ɡuːt]',     type:'deyim' },
      { de:'Wer wagt, gewinnt',                     tr:'Göze alan kazanır',                                phonetic:'[veːɐ vaːkt ɡəˈvɪnt]',         type:'deyim' },
      { de:'Die Sprache ist das Haus des Seins',    tr:'Dil, varlığın evidir (Heidegger)',                 phonetic:'[diː ˈʃpʁaːxə ɪst das haʊs]',  type:'cümle' },
      { de:'Das Geheimnis des Könnens liegt im Wollen', tr:'Yapabilmenin sırrı istemekte yatar',          phonetic:'[das ɡəˈhaɪmnɪs dɛs ˈkœnəns]', type:'cümle' },
      // === veritabani.json — C22 (23 cümle) ===
      { de:'Ein ökokritischer Ansatz wirft Fragen der Nachhaltigkeit auf.', tr:'Eko-eleştirel yaklaşım sürdürülebilirlik sorularını gündeme getirir.', type:'cümle', topic:'Edebi analiz', subTopic:'Eko-eleştiri', cefr:'C2.2' },
      { de:'Eine queertheoretische Perspektive problematisiert Normativität.', tr:'Queer teorik perspektif normativiteyi sorgular.', type:'cümle', topic:'Edebi analiz', subTopic:'Queer teori', cefr:'C2.2' },
      { de:'Ein neurowissenschaftlicher Ansatz erhellt die literarische Wahrnehmung.', tr:'Sinirbilimsel yaklaşım edebi algıyı aydınlatır.', type:'cümle', topic:'Edebi analiz', subTopic:'Bilişsel bilim', cefr:'C2.2' },
      { de:'Das Verhältnis von Mimesis und Diegesis muss hergestellt werden.', tr:'Mimesis ve diegesis ilişkisi kurulmalı.', type:'cümle', topic:'Edebi analiz', subTopic:'Mimesis', cefr:'C2.2' },
      { de:'Diegetische und metadiegetische Ebenen sind vorhanden.', tr:'Diegetik ve metadiegetik katmanlar var.', type:'cümle', topic:'Edebi analiz', subTopic:'Diegesis', cefr:'C2.2' },
      { de:'Eine semiologische Dekonstruktion sollte vorgenommen werden.', tr:'Semiyolojik çözümleme yapılmalı.', type:'cümle', topic:'Edebi analiz', subTopic:'Semiyoloji', cefr:'C2.2' },
      { de:'Kollektive Unterbewusstseinsreflexe sind vorhanden.', tr:'Kolektif bilinçdışı yansımalar mevcut.', type:'cümle', topic:'Edebi analiz', subTopic:'Bilinçdışı', cefr:'C2.2' },
      { de:'Symbolismus-Schichten müssen differenziert werden.', tr:'Simgecilik katmanları ayrıştırılmalı.', type:'cümle', topic:'Edebi analiz', subTopic:'Simgecilik', cefr:'C2.2' },
      { de:'Die ontologische Unbestimmtheit ist bewusst gewählt.', tr:'Ontolojik belirsizlik bilinçli.', type:'cümle', topic:'Edebi analiz', subTopic:'Ontoloji', cefr:'C2.2' },
      { de:'Die Seinsvergessenheit ist gegeben.', tr:'Varlık unutuluşu söz konusu.', type:'cümle', topic:'Felsefe', subTopic:'Varlık', cefr:'C2.2' },
      { de:'Der hermeneutische Zirkel muss überwunden werden.', tr:'Hermeneutik daire aşılmalı.', type:'cümle', topic:'Felsefe', subTopic:'Hermeneutik', cefr:'C2.2' },
      { de:'Vor dem Verstehen liegt ein Vorverständnis.', tr:'Yorum öncesi ön-anlayış var.', type:'cümle', topic:'Felsefe', subTopic:'Yorum', cefr:'C2.2' },
      { de:'Die Simulakrum-Ebene ist überschritten.', tr:'Simulakrum düzeyi aşıldı.', type:'cümle', topic:'Felsefe', subTopic:'Simülasyon', cefr:'C2.2' },
      { de:'Ein Zustand der Hyperrealität liegt vor.', tr:'Hipergerçeklik durumu söz konusu.', type:'cümle', topic:'Felsefe', subTopic:'Gerçeklik', cefr:'C2.2' },
      { de:'Die panoptische Gesellschaft ist realisiert.', tr:'Panoptikum toplumu gerçekleşti.', type:'cümle', topic:'Felsefe', subTopic:'Panoptikon', cefr:'C2.2' },
      { de:'Die Biomacht-Techniken haben sich verbreitet.', tr:'Biyoiktidar teknikleri yaygınlaştı.', type:'cümle', topic:'Felsefe', subTopic:'İktidar', cefr:'C2.2' },
      { de:'Ein Epistemewandel wird erlebt.', tr:'Episteme dönüşümü yaşanıyor.', type:'cümle', topic:'Felsefe', subTopic:'Episteme', cefr:'C2.2' },
      { de:'Das Deleuzianische Rhizom-Modell ist anwendbar.', tr:'Deleuze\'cü rhizom modeli uygulanabilir.', type:'cümle', topic:'Felsefe', subTopic:'Rhizom', cefr:'C2.2' },
      { de:'Der Deterritorialisierungsprozess hat begonnen.', tr:'Deterytoryalizasyon süreci başladı.', type:'cümle', topic:'Felsefe', subTopic:'Deterytoryalizasyon', cefr:'C2.2' },
      { de:'Es trägt Merkmale der kleinen Literatur.', tr:'Minor literatür özellikleri taşıyor.', type:'cümle', topic:'Edebi analiz', subTopic:'Minor', cefr:'C2.2' },
      { de:'Die Unterscheidung von Simulation und Imitation gibt es nicht.', tr:'Simülasyon ve taklit ayrımı yok.', type:'cümle', topic:'Felsefe', subTopic:'Simülasyon', cefr:'C2.2' },
      { de:'Die Gesellschaft des Spektakels ist realisiert.', tr:'Gösteri toplumu gerçekleşti.', type:'cümle', topic:'Medya', subTopic:'Gösteri', cefr:'C2.2' },
      { de:'Eine Subaltern-Studie ist erforderlich.', tr:'Altyazı okuması gerekli.', type:'cümle', topic:'Kültür', subTopic:'Altyazı', cefr:'C2.2' }
    ]
  }
};

/** Belirli bir seviye + kategorilerin düz listesini döndürür */
function veriGetirKategori(levelId, catId) {
  const lv = VERITABANI[levelId];
  if (!lv || !lv[catId]) return [];
  return lv[catId].map(w => ({ ...w }));
}

/** Belirli bir seviyenin tüm kategorilerini birleştirip döndürür (geriye dönük uyumluluk) */
function veriGetir(levelId) {
  return KATEGORILER.flatMap(k => veriGetirKategori(levelId, k.id));
}
